        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 08 12:08:39 2016
        MODULE ASSIGNRAIN__genmod
          INTERFACE 
            SUBROUTINE ASSIGNRAIN(TOTAL,PPT)
              REAL(KIND=4) :: TOTAL
              REAL(KIND=4) :: PPT(96)
            END SUBROUTINE ASSIGNRAIN
          END INTERFACE 
        END MODULE ASSIGNRAIN__genmod
