        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 08 12:08:47 2016
        MODULE AVERAGEVAL__genmod
          INTERFACE 
            FUNCTION AVERAGEVAL(ARR,NUMVAL)
              REAL(KIND=4) :: ARR(4500)
              INTEGER(KIND=4) :: NUMVAL
              REAL(KIND=4) :: AVERAGEVAL
            END FUNCTION AVERAGEVAL
          END INTERFACE 
        END MODULE AVERAGEVAL__genmod
