        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 08 12:08:45 2016
        MODULE CALCELP__genmod
          INTERFACE 
            FUNCTION CALCELP(AVGANG)
              REAL(KIND=4) :: AVGANG
              REAL(KIND=4) :: CALCELP
            END FUNCTION CALCELP
          END INTERFACE 
        END MODULE CALCELP__genmod
