        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 08 12:08:39 2016
        MODULE CALCFSUN__genmod
          INTERFACE 
            SUBROUTINE CALCFSUN(FBEAM,FSUN)
              REAL(KIND=4) :: FBEAM(96,3)
              REAL(KIND=4) :: FSUN(96)
            END SUBROUTINE CALCFSUN
          END INTERFACE 
        END MODULE CALCFSUN__genmod
