        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 08 12:08:41 2016
        MODULE CALCFSOIL__genmod
          INTERFACE 
            FUNCTION CALCFSOIL(WSOILMETHOD,SOILMOISTURE,SOILDATA,SMD1,  &
     &SMD2,WC1,WC2,SWPEXP)
              INTEGER(KIND=4) :: WSOILMETHOD
              REAL(KIND=4) :: SOILMOISTURE
              INTEGER(KIND=4) :: SOILDATA
              REAL(KIND=4) :: SMD1
              REAL(KIND=4) :: SMD2
              REAL(KIND=4) :: WC1
              REAL(KIND=4) :: WC2
              REAL(KIND=4) :: SWPEXP
              REAL(KIND=4) :: CALCFSOIL
            END FUNCTION CALCFSOIL
          END INTERFACE 
        END MODULE CALCFSOIL__genmod
