        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 08 12:08:45 2016
        MODULE CALCLAI__genmod
          INTERFACE 
            SUBROUTINE CALCLAI(NOLADATES,FLT,NOALLTREES,XMAX,YMAX,XSLOPE&
     &,YSLOPE,TOTLAITABLE)
              INTEGER(KIND=4) :: NOLADATES
              REAL(KIND=4) :: FLT(30,4500)
              INTEGER(KIND=4) :: NOALLTREES
              REAL(KIND=4) :: XMAX
              REAL(KIND=4) :: YMAX
              REAL(KIND=4) :: XSLOPE
              REAL(KIND=4) :: YSLOPE
              REAL(KIND=4) :: TOTLAITABLE(30)
            END SUBROUTINE CALCLAI
          END INTERFACE 
        END MODULE CALCLAI__genmod
