        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 08 12:08:43 2016
        MODULE CRANKNICHOLS__genmod
          INTERFACE 
            SUBROUTINE CRANKNICHOLS(NLAYER,LAYTHICK,SOILTK,SOILTEMP,    &
     &VOLHC,THERMCOND)
              INTEGER(KIND=4) :: NLAYER
              REAL(KIND=4) :: LAYTHICK(75)
              REAL(KIND=4) :: SOILTK
              REAL(KIND=4) :: SOILTEMP(75)
              REAL(KIND=4) :: VOLHC(75)
              REAL(KIND=4) :: THERMCOND(75)
            END SUBROUTINE CRANKNICHOLS
          END INTERFACE 
        END MODULE CRANKNICHOLS__genmod
