        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 08 12:08:45 2016
        MODULE DISTINTERP2__genmod
          INTERFACE 
            SUBROUTINE DISTINTERP2(IDAY,ISTART,NODATES,NOMAX,IDATEARR,  &
     &PARAMTABLE,PARAM)
              INTEGER(KIND=4) :: IDAY
              INTEGER(KIND=4) :: ISTART
              INTEGER(KIND=4) :: NODATES
              INTEGER(KIND=4) :: NOMAX
              INTEGER(KIND=4) :: IDATEARR(30)
              REAL(KIND=4) :: PARAMTABLE(20,30)
              REAL(KIND=4) :: PARAM(20)
            END SUBROUTINE DISTINTERP2
          END INTERFACE 
        END MODULE DISTINTERP2__genmod
