        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 08 12:08:41 2016
        MODULE ESOILFUN__genmod
          INTERFACE 
            FUNCTION ESOILFUN(SOILTK)
              REAL(KIND=4) :: SOILTK
              REAL(KIND=4) :: ESOILFUN
            END FUNCTION ESOILFUN
          END INTERFACE 
        END MODULE ESOILFUN__genmod
