        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 08 12:08:47 2016
        MODULE FINDLENGTH__genmod
          INTERFACE 
            FUNCTION FINDLENGTH(ARR,ARRLEN,MAXLEN,EMPTYVAL)
              INTEGER(KIND=4) :: ARRLEN
              REAL(KIND=4) :: ARR(ARRLEN)
              INTEGER(KIND=4) :: MAXLEN
              REAL(KIND=4) :: EMPTYVAL
              INTEGER(KIND=4) :: FINDLENGTH
            END FUNCTION FINDLENGTH
          END INTERFACE 
        END MODULE FINDLENGTH__genmod
