        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 08 12:08:43 2016
        MODULE HEATBALANCE__genmod
          INTERFACE 
            SUBROUTINE HEATBALANCE(NLAYER,FRACWATER,POREFRAC,TAIRK,     &
     &SOILTK,SOILTEMP,LAYTHICK,WATERGAIN,WATERLOSS,PPTGAIN,THERMCOND)
              INTEGER(KIND=4) :: NLAYER
              REAL(KIND=4) :: FRACWATER(75)
              REAL(KIND=4) :: POREFRAC(75)
              REAL(KIND=4) :: TAIRK
              REAL(KIND=4) :: SOILTK
              REAL(KIND=4) :: SOILTEMP(75)
              REAL(KIND=4) :: LAYTHICK(75)
              REAL(KIND=4) :: WATERGAIN(75)
              REAL(KIND=4) :: WATERLOSS(75)
              REAL(KIND=4) :: PPTGAIN(75)
              REAL(KIND=4) :: THERMCOND(75)
            END SUBROUTINE HEATBALANCE
          END INTERFACE 
        END MODULE HEATBALANCE__genmod
