        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 08 12:08:47 2016
        MODULE HEATEVAP__genmod
          INTERFACE 
            FUNCTION HEATEVAP(TAIR)
              REAL(KIND=4) :: TAIR
              REAL(KIND=4) :: HEATEVAP
            END FUNCTION HEATEVAP
          END INTERFACE 
        END MODULE HEATEVAP__genmod
