        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 08 12:08:46 2016
        MODULE INTERPOLATEDIST__genmod
          INTERFACE 
            SUBROUTINE INTERPOLATEDIST(IDAY,ISTART,FRACROOTTABLE,       &
     &NOROOTDATES,NOROOTSPEC,DATESROOT,FRACROOTSPEC,NROOTLAYER,         &
     &NALPHASPEC,FALPHATABLESPEC,DATESLIA,NOLIADATES,FALPHASPEC,NSPECIES&
     &,ISMAESPA)
              INTEGER(KIND=4) :: IDAY
              INTEGER(KIND=4) :: ISTART
              REAL(KIND=4) :: FRACROOTTABLE(75,30,4)
              INTEGER(KIND=4) :: NOROOTDATES
              INTEGER(KIND=4) :: NOROOTSPEC
              INTEGER(KIND=4) :: DATESROOT(30)
              REAL(KIND=4) :: FRACROOTSPEC(75,4)
              INTEGER(KIND=4) :: NROOTLAYER
              INTEGER(KIND=4) :: NALPHASPEC(4)
              REAL(KIND=4) :: FALPHATABLESPEC(20,30,4)
              INTEGER(KIND=4) :: DATESLIA(30,4)
              INTEGER(KIND=4) :: NOLIADATES(4)
              REAL(KIND=4) :: FALPHASPEC(20,4)
              INTEGER(KIND=4) :: NSPECIES
              LOGICAL(KIND=4) :: ISMAESPA
            END SUBROUTINE INTERPOLATEDIST
          END INTERFACE 
        END MODULE INTERPOLATEDIST__genmod
