        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 08 12:08:47 2016
        MODULE MONTH__genmod
          INTERFACE 
            FUNCTION MONTH(IDATE50)
              INTEGER(KIND=4) :: IDATE50
              INTEGER(KIND=4) :: MONTH
            END FUNCTION MONTH
          END INTERFACE 
        END MODULE MONTH__genmod
