        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 08 12:08:45 2016
        MODULE OUTPUTHIST__genmod
          INTERFACE 
            SUBROUTINE OUTPUTHIST(UFILE,HISTO,BINSIZE,NOTARGETS)
              INTEGER(KIND=4) :: UFILE
              REAL(KIND=4) :: HISTO(4500,200)
              REAL(KIND=4) :: BINSIZE
              INTEGER(KIND=4) :: NOTARGETS
            END SUBROUTINE OUTPUTHIST
          END INTERFACE 
        END MODULE OUTPUTHIST__genmod
