        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 08 12:08:46 2016
        MODULE READLIA__genmod
          INTERFACE 
            SUBROUTINE READLIA(UFILE,NALPHAI,ALPHA,FALPHAI,DATESLIAOUT, &
     &NOLIADATES)
              INTEGER(KIND=4) :: UFILE
              INTEGER(KIND=4) :: NALPHAI
              REAL(KIND=4) :: ALPHA(20)
              REAL(KIND=4) :: FALPHAI(20,30)
              INTEGER(KIND=4) :: DATESLIAOUT(30)
              INTEGER(KIND=4) :: NOLIADATES
            END SUBROUTINE READLIA
          END INTERFACE 
        END MODULE READLIA__genmod
