        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 08 12:08:46 2016
        MODULE READINFILT__genmod
          INTERFACE 
            SUBROUTINE READINFILT(UFILE,EXPINFI)
              INTEGER(KIND=4) :: UFILE
              REAL(KIND=4) :: EXPINFI
            END SUBROUTINE READINFILT
          END INTERFACE 
        END MODULE READINFILT__genmod
