        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 08 12:08:46 2016
        MODULE READWATCONTROL__genmod
          INTERFACE 
            SUBROUTINE READWATCONTROL(UFILE,KEEPWETI,KEEPDRYI,SIMTSOILI,&
     &REASSIGNRAINI,WSOILMETHODI,RETFUNCTIONI,EQUALUPTAKEI,USEMEASETI,  &
     &USEMEASSWI,SIMSOILEVAPI,USESTANDI)
              INTEGER(KIND=4) :: UFILE
              INTEGER(KIND=4) :: KEEPWETI
              INTEGER(KIND=4) :: KEEPDRYI
              INTEGER(KIND=4) :: SIMTSOILI
              INTEGER(KIND=4) :: REASSIGNRAINI
              INTEGER(KIND=4) :: WSOILMETHODI
              INTEGER(KIND=4) :: RETFUNCTIONI
              INTEGER(KIND=4) :: EQUALUPTAKEI
              INTEGER(KIND=4) :: USEMEASETI
              INTEGER(KIND=4) :: USEMEASSWI
              INTEGER(KIND=4) :: SIMSOILEVAPI
              INTEGER(KIND=4) :: USESTANDI
            END SUBROUTINE READWATCONTROL
          END INTERFACE 
        END MODULE READWATCONTROL__genmod
