        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 08 12:08:46 2016
        MODULE READHIST__genmod
          INTERFACE 
            SUBROUTINE READHIST(UFILE,IOHIST,BINSIZEI)
              INTEGER(KIND=4) :: UFILE
              INTEGER(KIND=4) :: IOHIST
              REAL(KIND=4) :: BINSIZEI
            END SUBROUTINE READHIST
          END INTERFACE 
        END MODULE READHIST__genmod
