        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 08 12:08:46 2016
        MODULE READINITPARS__genmod
          INTERFACE 
            SUBROUTINE READINITPARS(UFILE,INITWATERI,SOILTEMPI)
              INTEGER(KIND=4) :: UFILE
              REAL(KIND=4) :: INITWATERI(75)
              REAL(KIND=4) :: SOILTEMPI(75)
            END SUBROUTINE READINITPARS
          END INTERFACE 
        END MODULE READINITPARS__genmod
