        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 08 12:08:46 2016
        MODULE READCONTREES__genmod
          INTERFACE 
            SUBROUTINE READCONTREES(UFILE,NOALLTREES,DX,DY,XMAX,YMAX,   &
     &NOTREESI,NOTARGETSI,ITARGETSI,IPLOTSHAPE,WEIGHTSI)
              INTEGER(KIND=4) :: UFILE
              INTEGER(KIND=4) :: NOALLTREES
              REAL(KIND=4) :: DX(4500)
              REAL(KIND=4) :: DY(4500)
              REAL(KIND=4) :: XMAX
              REAL(KIND=4) :: YMAX
              INTEGER(KIND=4) :: NOTREESI
              INTEGER(KIND=4) :: NOTARGETSI
              INTEGER(KIND=4) :: ITARGETSI(4500)
              INTEGER(KIND=4) :: IPLOTSHAPE
              REAL(KIND=4) :: WEIGHTSI(4500)
            END SUBROUTINE READCONTREES
          END INTERFACE 
        END MODULE READCONTREES__genmod
