        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 08 12:08:46 2016
        MODULE READLAYPARS__genmod
          INTERFACE 
            SUBROUTINE READLAYPARS(UFILE,NLAYERI,LAYTHICKI,COREWATERI,  &
     &POREFRACI,DRAINLIMITI,FRACORGANICI)
              INTEGER(KIND=4) :: UFILE
              INTEGER(KIND=4) :: NLAYERI
              REAL(KIND=4) :: LAYTHICKI(75)
              REAL(KIND=4) :: COREWATERI
              REAL(KIND=4) :: POREFRACI(75)
              REAL(KIND=4) :: DRAINLIMITI(75)
              REAL(KIND=4) :: FRACORGANICI(75)
            END SUBROUTINE READLAYPARS
          END INTERFACE 
        END MODULE READLAYPARS__genmod
