        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 08 12:08:39 2016
        MODULE READLAT__genmod
          INTERFACE 
            SUBROUTINE READLAT(UFILE,ALAT,TTIMD)
              INTEGER(KIND=4) :: UFILE
              REAL(KIND=4) :: ALAT
              REAL(KIND=4) :: TTIMD
            END SUBROUTINE READLAT
          END INTERFACE 
        END MODULE READLAT__genmod
