        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 08 12:08:46 2016
        MODULE READSPECLIST__genmod
          INTERFACE 
            SUBROUTINE READSPECLIST(UFILE,NSPECIES,ISPECIESI)
              INTEGER(KIND=4) :: UFILE
              INTEGER(KIND=4) :: NSPECIES
              INTEGER(KIND=4) :: ISPECIESI(4500)
            END SUBROUTINE READSPECLIST
          END INTERFACE 
        END MODULE READSPECLIST__genmod
