        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 08 12:08:46 2016
        MODULE READSOILEVAPPARS__genmod
          INTERFACE 
            SUBROUTINE READSOILEVAPPARS(UFILE,DRYTHICKMINI,TORTPARI)
              INTEGER(KIND=4) :: UFILE
              REAL(KIND=4) :: DRYTHICKMINI
              REAL(KIND=4) :: TORTPARI
            END SUBROUTINE READSOILEVAPPARS
          END INTERFACE 
        END MODULE READSOILEVAPPARS__genmod
