        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 08 12:08:47 2016
        MODULE REVARRAY__genmod
          INTERFACE 
            SUBROUTINE REVARRAY(ARR,ARRLEN,NEL,NEWARR)
              INTEGER(KIND=4) :: ARRLEN
              REAL(KIND=4) :: ARR(ARRLEN)
              INTEGER(KIND=4) :: NEL
              REAL(KIND=4) :: NEWARR(ARRLEN)
            END SUBROUTINE REVARRAY
          END INTERFACE 
        END MODULE REVARRAY__genmod
