        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 08 12:08:39 2016
        MODULE SKIPMET__genmod
          INTERFACE 
            SUBROUTINE SKIPMET(MFLAG,NSTEP)
              INTEGER(KIND=4) :: MFLAG
              INTEGER(KIND=4) :: NSTEP
            END SUBROUTINE SKIPMET
          END INTERFACE 
        END MODULE SKIPMET__genmod
