        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 08 12:08:43 2016
        MODULE SOILRESCALC__genmod
          INTERFACE 
            SUBROUTINE SOILRESCALC(USEMEASSW,SOILCOND,ROOTRESIST,       &
     &ROOTMASS,ROOTLEN,LAYTHICK,ROOTRAD,NROOTLAYER,SOILR1,SOILR2)
              INTEGER(KIND=4) :: USEMEASSW
              REAL(KIND=4) :: SOILCOND(75)
              REAL(KIND=4) :: ROOTRESIST
              REAL(KIND=4) :: ROOTMASS(75)
              REAL(KIND=4) :: ROOTLEN(75)
              REAL(KIND=4) :: LAYTHICK(75)
              REAL(KIND=4) :: ROOTRAD
              INTEGER(KIND=4) :: NROOTLAYER
              REAL(KIND=4) :: SOILR1(75)
              REAL(KIND=4) :: SOILR2(75)
            END SUBROUTINE SOILRESCALC
          END INTERFACE 
        END MODULE SOILRESCALC__genmod
