        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 08 12:08:47 2016
        MODULE SUBERROR__genmod
          INTERFACE 
            SUBROUTINE SUBERROR(MESSAGE,IFLAG,IOERROR)
              CHARACTER(*) :: MESSAGE
              INTEGER(KIND=4) :: IFLAG
              INTEGER(KIND=4) :: IOERROR
            END SUBROUTINE SUBERROR
          END INTERFACE 
        END MODULE SUBERROR__genmod
