        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 08 12:08:45 2016
        MODULE TREEINTERP__genmod
          INTERFACE 
            SUBROUTINE TREEINTERP(IDAY,ISTART,NODATES,IDATEARR,         &
     &PARAMTABLE,NOTREES,PARAMS)
              INTEGER(KIND=4) :: IDAY
              INTEGER(KIND=4) :: ISTART
              INTEGER(KIND=4) :: NODATES
              INTEGER(KIND=4) :: IDATEARR(30)
              REAL(KIND=4) :: PARAMTABLE(30,4500)
              INTEGER(KIND=4) :: NOTREES
              REAL(KIND=4) :: PARAMS(4500)
            END SUBROUTINE TREEINTERP
          END INTERFACE 
        END MODULE TREEINTERP__genmod
