        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 08 12:08:43 2016
        MODULE VOLHCFUN__genmod
          INTERFACE 
            FUNCTION VOLHCFUN(POREFRAC,FRACWATER)
              REAL(KIND=4) :: POREFRAC
              REAL(KIND=4) :: FRACWATER
              REAL(KIND=4) :: VOLHCFUN
            END FUNCTION VOLHCFUN
          END INTERFACE 
        END MODULE VOLHCFUN__genmod
