        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 08 12:08:45 2016
        MODULE WATINTERP__genmod
          INTERFACE 
            SUBROUTINE WATINTERP(IDAY,ISTART,NODATES,IDATEARR,PARAMTABLE&
     &,PARAMS)
              INTEGER(KIND=4) :: IDAY
              INTEGER(KIND=4) :: ISTART
              INTEGER(KIND=4) :: NODATES
              INTEGER(KIND=4) :: IDATEARR(30)
              REAL(KIND=4) :: PARAMTABLE(30)
              REAL(KIND=4) :: PARAMS
            END SUBROUTINE WATINTERP
          END INTERFACE 
        END MODULE WATINTERP__genmod
