        !COMPILER-GENERATED INTERFACE MODULE: Thu Sep 08 12:08:42 2016
        MODULE ZEROSTART__genmod
          INTERFACE 
            SUBROUTINE ZEROSTART(HISTO,CANOPYDIMS)
              REAL(KIND=4) :: HISTO(4500,200)
              REAL(KIND=4) :: CANOPYDIMS(6)
            END SUBROUTINE ZEROSTART
          END INTERFACE 
        END MODULE ZEROSTART__genmod
