        !COMPILER-GENERATED INTERFACE MODULE: Wed Nov 23 16:30:01 2016
        MODULE ASSIGNFRACROOT__genmod
          INTERFACE 
            SUBROUTINE ASSIGNFRACROOT(ROOTBETA,FRACROOT,NROOTLAYER,     &
     &LAYTHICK)
              REAL(KIND=4) :: ROOTBETA
              REAL(KIND=4) :: FRACROOT(51)
              INTEGER(KIND=4) :: NROOTLAYER
              REAL(KIND=4) :: LAYTHICK(51)
            END SUBROUTINE ASSIGNFRACROOT
          END INTERFACE 
        END MODULE ASSIGNFRACROOT__genmod
