        !COMPILER-GENERATED INTERFACE MODULE: Wed Nov 23 16:30:01 2016
        MODULE CLOSEF__genmod
          INTERFACE 
            SUBROUTINE CLOSEF
            END SUBROUTINE CLOSEF
          END INTERFACE 
        END MODULE CLOSEF__genmod
