        !COMPILER-GENERATED INTERFACE MODULE: Thu Apr 28 16:12:47 2016
        MODULE DISTINTERP__genmod
          INTERFACE 
            SUBROUTINE DISTINTERP(IDAY,ISTART,NODATES,NOMAX,IDATEARR,   &
     &PARAMTABLE,PARAM)
              INTEGER(KIND=4) :: IDAY
              INTEGER(KIND=4) :: ISTART
              INTEGER(KIND=4) :: NODATES
              INTEGER(KIND=4) :: NOMAX
              INTEGER(KIND=4) :: IDATEARR(45)
              REAL(KIND=4) :: PARAMTABLE(51,45)
              REAL(KIND=4) :: PARAM(51)
            END SUBROUTINE DISTINTERP
          END INTERFACE 
        END MODULE DISTINTERP__genmod
