        !COMPILER-GENERATED INTERFACE MODULE: Thu Apr 28 16:12:43 2016
        MODULE DIVFOURNEAR__genmod
          INTERFACE 
            FUNCTION DIVFOURNEAR(NUM)
              INTEGER(KIND=4) :: NUM
              INTEGER(KIND=4) :: DIVFOURNEAR
            END FUNCTION DIVFOURNEAR
          END INTERFACE 
        END MODULE DIVFOURNEAR__genmod
