        !COMPILER-GENERATED INTERFACE MODULE: Thu Apr 28 16:12:43 2016
        MODULE HEATEVAP__genmod
          INTERFACE 
            FUNCTION HEATEVAP(TAIR)
              REAL(KIND=4) :: TAIR
              REAL(KIND=4) :: HEATEVAP
            END FUNCTION HEATEVAP
          END INTERFACE 
        END MODULE HEATEVAP__genmod
