        !COMPILER-GENERATED INTERFACE MODULE: Wed Nov 30 18:40:55 2016
        MODULE JDATE__genmod
          INTERFACE 
            FUNCTION JDATE(IDATE50)
              INTEGER(KIND=4) :: IDATE50
              INTEGER(KIND=4) :: JDATE
            END FUNCTION JDATE
          END INTERFACE 
        END MODULE JDATE__genmod
