        !COMPILER-GENERATED INTERFACE MODULE: Thu Apr 28 16:12:43 2016
        MODULE MONTH__genmod
          INTERFACE 
            FUNCTION MONTH(IDATE50)
              INTEGER(KIND=4) :: IDATE50
              INTEGER(KIND=4) :: MONTH
            END FUNCTION MONTH
          END INTERFACE 
        END MODULE MONTH__genmod
