        !COMPILER-GENERATED INTERFACE MODULE: Thu Apr 28 18:03:55 2016
        MODULE PSILOBJFUN__genmod
          INTERFACE 
            FUNCTION PSILOBJFUN(PSILIN,EXTRAPARS,EXTRAINT)
              REAL(KIND=4) :: PSILIN
              REAL(KIND=4) :: EXTRAPARS(75)
              INTEGER(KIND=4) :: EXTRAINT(10)
              REAL(KIND=4) :: PSILOBJFUN
            END FUNCTION PSILOBJFUN
          END INTERFACE 
        END MODULE PSILOBJFUN__genmod
