        !COMPILER-GENERATED INTERFACE MODULE: Thu Apr 28 16:12:48 2016
        MODULE READPROP__genmod
          INTERFACE 
            SUBROUTINE READPROP(UFILE,NOAGEC,NOAGEP,PROPCI,PROPPI)
              INTEGER(KIND=4) :: UFILE
              INTEGER(KIND=4) :: NOAGEC
              INTEGER(KIND=4) :: NOAGEP
              REAL(KIND=4) :: PROPCI(3)
              REAL(KIND=4) :: PROPPI(3)
            END SUBROUTINE READPROP
          END INTERFACE 
        END MODULE READPROP__genmod
