        !COMPILER-GENERATED INTERFACE MODULE: Thu Apr 28 16:12:48 2016
        MODULE READAERO__genmod
          INTERFACE 
            SUBROUTINE READAERO(UFILE,EXTWINDI)
              INTEGER(KIND=4) :: UFILE
              REAL(KIND=4) :: EXTWINDI
            END SUBROUTINE READAERO
          END INTERFACE 
        END MODULE READAERO__genmod
