        !COMPILER-GENERATED INTERFACE MODULE: Wed Nov 23 16:30:01 2016
        MODULE READCROWN__genmod
          INTERFACE 
            SUBROUTINE READCROWN(UFILE,JSHAPE,SHAPE)
              INTEGER(KIND=4) :: UFILE
              INTEGER(KIND=4) :: JSHAPE
              REAL(KIND=4) :: SHAPE
            END SUBROUTINE READCROWN
          END INTERFACE 
        END MODULE READCROWN__genmod
