        !COMPILER-GENERATED INTERFACE MODULE: Thu Apr 28 16:12:48 2016
        MODULE READINFILT__genmod
          INTERFACE 
            SUBROUTINE READINFILT(UFILE,EXPINFI)
              INTEGER(KIND=4) :: UFILE
              REAL(KIND=4) :: EXPINFI
            END SUBROUTINE READINFILT
          END INTERFACE 
        END MODULE READINFILT__genmod
