        !COMPILER-GENERATED INTERFACE MODULE: Wed Nov 30 18:41:00 2016
        MODULE READPLOT__genmod
          INTERFACE 
            SUBROUTINE READPLOT(UFILE,X0I,Y0I,XMAXI,YMAXI,NOALLTREESI,  &
     &XSLOPEI,YSLOPEI,BEARI,SHADEHTI,STOCKING,IPLOTSHAPE,WATBALAREAI)
              INTEGER(KIND=4) :: UFILE
              REAL(KIND=4) :: X0I
              REAL(KIND=4) :: Y0I
              REAL(KIND=4) :: XMAXI
              REAL(KIND=4) :: YMAXI
              INTEGER(KIND=4) :: NOALLTREESI
              REAL(KIND=4) :: XSLOPEI
              REAL(KIND=4) :: YSLOPEI
              REAL(KIND=4) :: BEARI
              REAL(KIND=4) :: SHADEHTI
              REAL(KIND=4) :: STOCKING
              INTEGER(KIND=4) :: IPLOTSHAPE
              REAL(KIND=4) :: WATBALAREAI
            END SUBROUTINE READPLOT
          END INTERFACE 
        END MODULE READPLOT__genmod
