        !COMPILER-GENERATED INTERFACE MODULE: Thu Apr 28 16:12:48 2016
        MODULE READCROWN__genmod
          INTERFACE 
            SUBROUTINE READCROWN(UFILE,JSHAPE,SHAPE)
              INTEGER(KIND=4) :: UFILE
              INTEGER(KIND=4) :: JSHAPE
              REAL(KIND=4) :: SHAPE
            END SUBROUTINE READCROWN
          END INTERFACE 
        END MODULE READCROWN__genmod
