        !COMPILER-GENERATED INTERFACE MODULE: Thu Apr 28 18:03:56 2016
        MODULE READLAT__genmod
          INTERFACE 
            SUBROUTINE READLAT(UFILE,ALAT,TTIMD)
              INTEGER(KIND=4) :: UFILE
              REAL(KIND=4) :: ALAT
              REAL(KIND=4) :: TTIMD
            END SUBROUTINE READLAT
          END INTERFACE 
        END MODULE READLAT__genmod
