        !COMPILER-GENERATED INTERFACE MODULE: Wed Nov 23 16:30:01 2016
        MODULE READVSTRESS__genmod
          INTERFACE 
            SUBROUTINE READVSTRESS(UFILE,VPARAI,VPARBI,VPARCI,VFUNI)
              INTEGER(KIND=4) :: UFILE
              REAL(KIND=4) :: VPARAI
              REAL(KIND=4) :: VPARBI
              REAL(KIND=4) :: VPARCI
              INTEGER(KIND=4) :: VFUNI
            END SUBROUTINE READVSTRESS
          END INTERFACE 
        END MODULE READVSTRESS__genmod
