        !COMPILER-GENERATED INTERFACE MODULE: Wed Nov 30 18:41:00 2016
        MODULE READSPECIES__genmod
          INTERFACE 
            SUBROUTINE READSPECIES(UFILE,NSPECIES,SPECIESNAMES,PHYFILES,&
     &STRFILES)
              INTEGER(KIND=4) :: UFILE
              INTEGER(KIND=4) :: NSPECIES
              CHARACTER(LEN=30) :: SPECIESNAMES(5)
              CHARACTER(LEN=30) :: PHYFILES(5)
              CHARACTER(LEN=30) :: STRFILES(5)
            END SUBROUTINE READSPECIES
          END INTERFACE 
        END MODULE READSPECIES__genmod
