        !COMPILER-GENERATED INTERFACE MODULE: Thu Apr 28 16:12:47 2016
        MODULE READLAYPARS__genmod
          INTERFACE 
            SUBROUTINE READLAYPARS(UFILE,NLAYERI,LAYTHICKI,COREWATERI,  &
     &POREFRACI,DRAINLIMITI,FRACORGANICI,IWATTABLAYERI,PLATDRAINI)
              INTEGER(KIND=4) :: UFILE
              INTEGER(KIND=4) :: NLAYERI
              REAL(KIND=4) :: LAYTHICKI(51)
              REAL(KIND=4) :: COREWATERI
              REAL(KIND=4) :: POREFRACI(51)
              REAL(KIND=4) :: DRAINLIMITI(51)
              REAL(KIND=4) :: FRACORGANICI(51)
              INTEGER(KIND=4) :: IWATTABLAYERI
              REAL(KIND=4) :: PLATDRAINI
            END SUBROUTINE READLAYPARS
          END INTERFACE 
        END MODULE READLAYPARS__genmod
