        !COMPILER-GENERATED INTERFACE MODULE: Thu Apr 28 16:12:48 2016
        MODULE READCCSCEN__genmod
          INTERFACE 
            SUBROUTINE READCCSCEN(UFILE,ICC,CO2INCI,TINCI)
              INTEGER(KIND=4) :: UFILE
              INTEGER(KIND=4) :: ICC
              REAL(KIND=4) :: CO2INCI
              REAL(KIND=4) :: TINCI
            END SUBROUTINE READCCSCEN
          END INTERFACE 
        END MODULE READCCSCEN__genmod
