        !COMPILER-GENERATED INTERFACE MODULE: Wed Nov 23 16:30:01 2016
        MODULE READALLOM__genmod
          INTERFACE 
            SUBROUTINE READALLOM(UFILE,COEFFTI,EXPONTI,WINTERCI,BCOEFFTI&
     &,BEXPONTI,BINTERCI,RCOEFFTI,REXPONTI,RINTERCI,FRFRACI)
              INTEGER(KIND=4) :: UFILE
              REAL(KIND=4) :: COEFFTI
              REAL(KIND=4) :: EXPONTI
              REAL(KIND=4) :: WINTERCI
              REAL(KIND=4) :: BCOEFFTI
              REAL(KIND=4) :: BEXPONTI
              REAL(KIND=4) :: BINTERCI
              REAL(KIND=4) :: RCOEFFTI
              REAL(KIND=4) :: REXPONTI
              REAL(KIND=4) :: RINTERCI
              REAL(KIND=4) :: FRFRACI
            END SUBROUTINE READALLOM
          END INTERFACE 
        END MODULE READALLOM__genmod
