        !COMPILER-GENERATED INTERFACE MODULE: Thu Apr 28 16:12:48 2016
        MODULE READLEAFN__genmod
          INTERFACE 
            SUBROUTINE READLEAFN(UFILE,MODELJM,MODELRD,NOLAY,NOAGEP,    &
     &NONDATES,DATESN,VALUESN)
              INTEGER(KIND=4) :: UFILE
              INTEGER(KIND=4) :: MODELJM
              INTEGER(KIND=4) :: MODELRD
              INTEGER(KIND=4) :: NOLAY
              INTEGER(KIND=4) :: NOAGEP
              INTEGER(KIND=4) :: NONDATES
              INTEGER(KIND=4) :: DATESN(45)
              REAL(KIND=4) :: VALUESN(45,15,3)
            END SUBROUTINE READLEAFN
          END INTERFACE 
        END MODULE READLEAFN__genmod
