        !COMPILER-GENERATED INTERFACE MODULE: Wed Nov 30 18:41:00 2016
        MODULE READSOILEVAPPARS__genmod
          INTERFACE 
            SUBROUTINE READSOILEVAPPARS(UFILE,DRYTHICKMINI,TORTPARI,    &
     &DRYTHERMI)
              INTEGER(KIND=4) :: UFILE
              REAL(KIND=4) :: DRYTHICKMINI
              REAL(KIND=4) :: TORTPARI
              REAL(KIND=4) :: DRYTHERMI
            END SUBROUTINE READSOILEVAPPARS
          END INTERFACE 
        END MODULE READSOILEVAPPARS__genmod
