        !COMPILER-GENERATED INTERFACE MODULE: Thu Apr 28 16:12:47 2016
        MODULE READINITPARS__genmod
          INTERFACE 
            SUBROUTINE READINITPARS(UFILE,INITWATERI,SOILTEMPI)
              INTEGER(KIND=4) :: UFILE
              REAL(KIND=4) :: INITWATERI(51)
              REAL(KIND=4) :: SOILTEMPI(51)
            END SUBROUTINE READINITPARS
          END INTERFACE 
        END MODULE READINITPARS__genmod
