        !COMPILER-GENERATED INTERFACE MODULE: Wed Nov 30 18:40:55 2016
        MODULE SOILCONDFUN2__genmod
          INTERFACE 
            FUNCTION SOILCONDFUN2(SOILWP,KSAT,BPAR,PSIE)
              REAL(KIND=4) :: SOILWP
              REAL(KIND=4) :: KSAT
              REAL(KIND=4) :: BPAR
              REAL(KIND=4) :: PSIE
              REAL(KIND=4) :: SOILCONDFUN2
            END FUNCTION SOILCONDFUN2
          END INTERFACE 
        END MODULE SOILCONDFUN2__genmod
