        !COMPILER-GENERATED INTERFACE MODULE: Thu Apr 28 18:03:55 2016
        MODULE THERMCONDFUN__genmod
          INTERFACE 
            FUNCTION THERMCONDFUN(I,SOILWP,FRACWATER,POREFRAC,BPAR,     &
     &FRACORGANIC,RETFUNCTION)
              INTEGER(KIND=4) :: I
              REAL(KIND=4) :: SOILWP
              REAL(KIND=4) :: FRACWATER
              REAL(KIND=4) :: POREFRAC
              REAL(KIND=4) :: BPAR
              REAL(KIND=4) :: FRACORGANIC
              INTEGER(KIND=4) :: RETFUNCTION
              REAL(KIND=4) :: THERMCONDFUN
            END FUNCTION THERMCONDFUN
          END INTERFACE 
        END MODULE THERMCONDFUN__genmod
