        !COMPILER-GENERATED INTERFACE MODULE: Wed Nov 23 16:29:58 2016
        MODULE ZEROIPTTABLE__genmod
          INTERFACE 
            SUBROUTINE ZEROIPTTABLE(TLEAFTABLE,APARTABLE,ANIRTABLE,     &
     &ATHRTABLE,ETTABLE,HTABLE,GSCTABLE,PSILTABLE,AREATOT,ITAR,IPT)
              REAL(KIND=4) :: TLEAFTABLE(5000,5000)
              REAL(KIND=4) :: APARTABLE(5000,5000)
              REAL(KIND=4) :: ANIRTABLE(5000,5000)
              REAL(KIND=4) :: ATHRTABLE(5000,5000)
              REAL(KIND=4) :: ETTABLE(5000,5000)
              REAL(KIND=4) :: HTABLE(5000,5000)
              REAL(KIND=4) :: GSCTABLE(5000,5000)
              REAL(KIND=4) :: PSILTABLE(5000,5000)
              REAL(KIND=4) :: AREATOT
              INTEGER(KIND=4) :: ITAR
              INTEGER(KIND=4) :: IPT
            END SUBROUTINE ZEROIPTTABLE
          END INTERFACE 
        END MODULE ZEROIPTTABLE__genmod
