        !COMPILER-GENERATED INTERFACE MODULE: Thu Apr 28 16:53:48 2016
        MODULE ZEROFSOIL__genmod
          INTERFACE 
            SUBROUTINE ZEROFSOIL(FSOIL1,NSUMMED,TOTTMP)
              REAL(KIND=4) :: FSOIL1
              INTEGER(KIND=4) :: NSUMMED
              REAL(KIND=4) :: TOTTMP
            END SUBROUTINE ZEROFSOIL
          END INTERFACE 
        END MODULE ZEROFSOIL__genmod
