        !COMPILER-GENERATED INTERFACE MODULE: Thu Apr 28 16:53:48 2016
        MODULE ZEROSTART__genmod
          INTERFACE 
            SUBROUTINE ZEROSTART(HISTO,CANOPYDIMS)
              REAL(KIND=4) :: HISTO(5000,200)
              REAL(KIND=4) :: CANOPYDIMS(6)
            END SUBROUTINE ZEROSTART
          END INTERFACE 
        END MODULE ZEROSTART__genmod
