        !COMPILER-GENERATED INTERFACE MODULE: Tue May 03 14:08:23 2016
        MODULE CALCFSUN__genmod
          INTERFACE 
            SUBROUTINE CALCFSUN(FBEAM,FSUN)
              REAL(KIND=4) :: FBEAM(96,3)
              REAL(KIND=4) :: FSUN(96)
            END SUBROUTINE CALCFSUN
          END INTERFACE 
        END MODULE CALCFSUN__genmod
