        !COMPILER-GENERATED INTERFACE MODULE: Tue May 03 14:08:22 2016
        MODULE CALCELP__genmod
          INTERFACE 
            FUNCTION CALCELP(AVGANG)
              REAL(KIND=4) :: AVGANG
              REAL(KIND=4) :: CALCELP
            END FUNCTION CALCELP
          END INTERFACE 
        END MODULE CALCELP__genmod
