        !COMPILER-GENERATED INTERFACE MODULE: Tue May 03 14:08:23 2016
        MODULE CALCTSOIL__genmod
          INTERFACE 
            SUBROUTINE CALCTSOIL(TAIR,TSOIL)
              REAL(KIND=4) :: TAIR(96)
              REAL(KIND=4) :: TSOIL(96)
            END SUBROUTINE CALCTSOIL
          END INTERFACE 
        END MODULE CALCTSOIL__genmod
