        !COMPILER-GENERATED INTERFACE MODULE: Tue May 03 14:08:22 2016
        MODULE CALCLAI__genmod
          INTERFACE 
            SUBROUTINE CALCLAI(NOLADATES,FLT,NOALLTREES,XMAX,YMAX,XSLOPE&
     &,YSLOPE,TOTLAITABLE)
              INTEGER(KIND=4) :: NOLADATES
              REAL(KIND=4) :: FLT(1000,5000)
              INTEGER(KIND=4) :: NOALLTREES
              REAL(KIND=4) :: XMAX
              REAL(KIND=4) :: YMAX
              REAL(KIND=4) :: XSLOPE
              REAL(KIND=4) :: YSLOPE
              REAL(KIND=4) :: TOTLAITABLE(1000)
            END SUBROUTINE CALCLAI
          END INTERFACE 
        END MODULE CALCLAI__genmod
