        !COMPILER-GENERATED INTERFACE MODULE: Tue May 03 14:08:24 2016
        MODULE DAYJUL__genmod
          INTERFACE 
            FUNCTION DAYJUL(IDATE)
              INTEGER(KIND=4) :: IDATE
              INTEGER(KIND=4) :: DAYJUL
            END FUNCTION DAYJUL
          END INTERFACE 
        END MODULE DAYJUL__genmod
