        !COMPILER-GENERATED INTERFACE MODULE: Tue May 03 14:08:32 2016
        MODULE DIVFOURNEAR__genmod
          INTERFACE 
            FUNCTION DIVFOURNEAR(NUM)
              INTEGER(KIND=4) :: NUM
              INTEGER(KIND=4) :: DIVFOURNEAR
            END FUNCTION DIVFOURNEAR
          END INTERFACE 
        END MODULE DIVFOURNEAR__genmod
