        !COMPILER-GENERATED INTERFACE MODULE: Tue May 03 14:08:22 2016
        MODULE LADCHOOSE__genmod
          INTERFACE 
            SUBROUTINE LADCHOOSE(IDAY,ISTART,NSPECIES,NOLADDATES,       &
     &DATESLAD,BPTTABLESPEC,BPTSPEC)
              INTEGER(KIND=4) :: IDAY
              INTEGER(KIND=4) :: ISTART
              INTEGER(KIND=4) :: NSPECIES
              INTEGER(KIND=4) :: NOLADDATES(4)
              INTEGER(KIND=4) :: DATESLAD(1000,4)
              REAL(KIND=4) :: BPTTABLESPEC(8,3,4,1000)
              REAL(KIND=4) :: BPTSPEC(8,3,4)
            END SUBROUTINE LADCHOOSE
          END INTERFACE 
        END MODULE LADCHOOSE__genmod
