        !COMPILER-GENERATED INTERFACE MODULE: Tue May 03 14:08:22 2016
        MODULE PHYINTERP2__genmod
          INTERFACE 
            SUBROUTINE PHYINTERP2(IDATE,NODATES,IDATEARR,PARAMTABLE,    &
     &PARAM)
              INTEGER(KIND=4) :: IDATE
              INTEGER(KIND=4) :: NODATES
              INTEGER(KIND=4) :: IDATEARR(1000)
              REAL(KIND=4) :: PARAMTABLE(1000)
              REAL(KIND=4) :: PARAM
            END SUBROUTINE PHYINTERP2
          END INTERFACE 
        END MODULE PHYINTERP2__genmod
