        !COMPILER-GENERATED INTERFACE MODULE: Tue May 03 14:08:23 2016
        MODULE READARRAY__genmod
          INTERFACE 
            SUBROUTINE READARRAY(UFILE,INDEX,NDATESI,DATESI,RATES)
              INTEGER(KIND=4) :: UFILE
              INTEGER(KIND=4) :: INDEX
              INTEGER(KIND=4) :: NDATESI
              INTEGER(KIND=4) :: DATESI(1000)
              REAL(KIND=4) :: RATES(1000)
            END SUBROUTINE READARRAY
          END INTERFACE 
        END MODULE READARRAY__genmod
