        !COMPILER-GENERATED INTERFACE MODULE: Tue May 03 14:08:23 2016
        MODULE READRB__genmod
          INTERFACE 
            SUBROUTINE READRB(UFILE,RMBI,Q10BI,RTEMPBI)
              INTEGER(KIND=4) :: UFILE
              REAL(KIND=4) :: RMBI
              REAL(KIND=4) :: Q10BI
              REAL(KIND=4) :: RTEMPBI
            END SUBROUTINE READRB
          END INTERFACE 
        END MODULE READRB__genmod
