        !COMPILER-GENERATED INTERFACE MODULE: Tue May 03 14:08:23 2016
        MODULE READWATCONTROL__genmod
          INTERFACE 
            SUBROUTINE READWATCONTROL(UFILE,KEEPWETI,KEEPDRYI,SIMTSOILI,&
     &REASSIGNRAINI,WSOILMETHODI,RETFUNCTIONI,EQUALUPTAKEI,USEMEASETI,  &
     &USEMEASSWI,SIMSOILEVAPI,USESTANDI,SIMSTOREI,ISIMWATTABI)
              INTEGER(KIND=4) :: UFILE
              INTEGER(KIND=4) :: KEEPWETI
              INTEGER(KIND=4) :: KEEPDRYI
              INTEGER(KIND=4) :: SIMTSOILI
              INTEGER(KIND=4) :: REASSIGNRAINI
              INTEGER(KIND=4) :: WSOILMETHODI
              INTEGER(KIND=4) :: RETFUNCTIONI
              INTEGER(KIND=4) :: EQUALUPTAKEI
              INTEGER(KIND=4) :: USEMEASETI
              INTEGER(KIND=4) :: USEMEASSWI
              INTEGER(KIND=4) :: SIMSOILEVAPI
              INTEGER(KIND=4) :: USESTANDI
              INTEGER(KIND=4) :: SIMSTOREI
              INTEGER(KIND=4) :: ISIMWATTABI
            END SUBROUTINE READWATCONTROL
          END INTERFACE 
        END MODULE READWATCONTROL__genmod
