        !COMPILER-GENERATED INTERFACE MODULE: Tue May 03 14:08:23 2016
        MODULE READCROWN__genmod
          INTERFACE 
            SUBROUTINE READCROWN(UFILE,JSHAPE,SHAPE)
              INTEGER(KIND=4) :: UFILE
              INTEGER(KIND=4) :: JSHAPE
              REAL(KIND=4) :: SHAPE
            END SUBROUTINE READCROWN
          END INTERFACE 
        END MODULE READCROWN__genmod
