        !COMPILER-GENERATED INTERFACE MODULE: Tue May 03 14:08:23 2016
        MODULE READDATES__genmod
          INTERFACE 
            SUBROUTINE READDATES(UFILE,ISTART,IEND,NSTEPI)
              INTEGER(KIND=4) :: UFILE
              INTEGER(KIND=4) :: ISTART
              INTEGER(KIND=4) :: IEND
              INTEGER(KIND=4) :: NSTEPI
            END SUBROUTINE READDATES
          END INTERFACE 
        END MODULE READDATES__genmod
