        !COMPILER-GENERATED INTERFACE MODULE: Tue May 03 14:08:23 2016
        MODULE READAERO__genmod
          INTERFACE 
            SUBROUTINE READAERO(UFILE,EXTWINDI)
              INTEGER(KIND=4) :: UFILE
              REAL(KIND=4) :: EXTWINDI
            END SUBROUTINE READAERO
          END INTERFACE 
        END MODULE READAERO__genmod
