        !COMPILER-GENERATED INTERFACE MODULE: Tue May 03 14:08:23 2016
        MODULE RESTARTMETF__genmod
          INTERFACE 
            SUBROUTINE RESTARTMETF(ISTART,MSTART,MFLAG)
              INTEGER(KIND=4) :: ISTART
              INTEGER(KIND=4) :: MSTART
              INTEGER(KIND=4) :: MFLAG
            END SUBROUTINE RESTARTMETF
          END INTERFACE 
        END MODULE RESTARTMETF__genmod
