        !COMPILER-GENERATED INTERFACE MODULE: Tue May 03 14:08:24 2016
        MODULE TPROFILE__genmod
          INTERFACE 
            SUBROUTINE TPROFILE(IPT,ITAR,LAYER,MLAYERI,TLEAFTABLE,NUMPNT&
     &,TLEAFLAYER)
              INTEGER(KIND=4) :: MLAYERI
              INTEGER(KIND=4) :: IPT
              INTEGER(KIND=4) :: ITAR
              INTEGER(KIND=4) :: LAYER(100)
              REAL(KIND=4) :: TLEAFTABLE(5000,4000)
              INTEGER(KIND=4) :: NUMPNT
              REAL(KIND=4) :: TLEAFLAYER(MLAYERI)
            END SUBROUTINE TPROFILE
          END INTERFACE 
        END MODULE TPROFILE__genmod
