        !COMPILER-GENERATED INTERFACE MODULE: Tue May 03 14:08:22 2016
        MODULE TREEINTERP2__genmod
          INTERFACE 
            SUBROUTINE TREEINTERP2(IDAY,ISTART,NODATES,IDATEARR,        &
     &PARAMTABLE,NOTREES,PARAMS)
              INTEGER(KIND=4) :: IDAY
              INTEGER(KIND=4) :: ISTART
              INTEGER(KIND=4) :: NODATES
              INTEGER(KIND=4) :: IDATEARR(1000)
              REAL(KIND=4) :: PARAMTABLE(1000)
              INTEGER(KIND=4) :: NOTREES
              REAL(KIND=4) :: PARAMS
            END SUBROUTINE TREEINTERP2
          END INTERFACE 
        END MODULE TREEINTERP2__genmod
