        !COMPILER-GENERATED INTERFACE MODULE: Tue May 03 14:08:20 2016
        MODULE ZEROSTART__genmod
          INTERFACE 
            SUBROUTINE ZEROSTART(HISTO,CANOPYDIMS)
              REAL(KIND=4) :: HISTO(5000,200)
              REAL(KIND=4) :: CANOPYDIMS(6)
            END SUBROUTINE ZEROSTART
          END INTERFACE 
        END MODULE ZEROSTART__genmod
