        !COMPILER-GENERATED INTERFACE MODULE: Tue May 03 14:08:20 2016
        MODULE ZEROD__genmod
          INTERFACE 
            SUBROUTINE ZEROD(TDYAB,TOTCO2,TOTRESPF,TOTRESPWM,TOTRESPB,  &
     &TOTRESPCR,TOTRESPFR,TOTH2O,TOTHFX,WSOILMEAN,WSOILROOTMEAN,SWPMEAN,&
     &PPTTOT,ETMMTOT,ETMEASTOT,DISCHARGETOT,SOILEVAPTOT,FSOILMEAN,      &
     &TFALLTOT,QHTOT,QETOT,QNTOT,QCTOT,RADINTERCTOT)
              REAL(KIND=4) :: TDYAB(5000,3)
              REAL(KIND=4) :: TOTCO2(5000)
              REAL(KIND=4) :: TOTRESPF(5000)
              REAL(KIND=4) :: TOTRESPWM(5000)
              REAL(KIND=4) :: TOTRESPB(5000)
              REAL(KIND=4) :: TOTRESPCR(5000)
              REAL(KIND=4) :: TOTRESPFR(5000)
              REAL(KIND=4) :: TOTH2O(5000)
              REAL(KIND=4) :: TOTHFX(5000)
              REAL(KIND=4) :: WSOILMEAN
              REAL(KIND=4) :: WSOILROOTMEAN
              REAL(KIND=4) :: SWPMEAN
              REAL(KIND=4) :: PPTTOT
              REAL(KIND=4) :: ETMMTOT
              REAL(KIND=4) :: ETMEASTOT
              REAL(KIND=4) :: DISCHARGETOT
              REAL(KIND=4) :: SOILEVAPTOT
              REAL(KIND=4) :: FSOILMEAN
              REAL(KIND=4) :: TFALLTOT
              REAL(KIND=4) :: QHTOT
              REAL(KIND=4) :: QETOT
              REAL(KIND=4) :: QNTOT
              REAL(KIND=4) :: QCTOT
              REAL(KIND=4) :: RADINTERCTOT
            END SUBROUTINE ZEROD
          END INTERFACE 
        END MODULE ZEROD__genmod
