        !COMPILER-GENERATED INTERFACE MODULE: Tue Sep 06 12:06:59 2016
        MODULE ASSIGNSOILWATER__genmod
          INTERFACE 
            SUBROUTINE ASSIGNSOILWATER(WSOILMETHOD,USEMEASSW,SWMIN,SWMAX&
     &,SOILMOIST,WSOILROOT,SOILDEPTH,SOILDATA,SOILMOISTURE)
              INTEGER(KIND=4) :: WSOILMETHOD
              INTEGER(KIND=4) :: USEMEASSW
              REAL(KIND=4) :: SWMIN
              REAL(KIND=4) :: SWMAX
              REAL(KIND=4) :: SOILMOIST
              REAL(KIND=4) :: WSOILROOT
              REAL(KIND=4) :: SOILDEPTH
              INTEGER(KIND=4) :: SOILDATA
              REAL(KIND=4) :: SOILMOISTURE
            END SUBROUTINE ASSIGNSOILWATER
          END INTERFACE 
        END MODULE ASSIGNSOILWATER__genmod
