        !COMPILER-GENERATED INTERFACE MODULE: Tue Sep 06 12:06:39 2016
        MODULE AVERAGEVAL__genmod
          INTERFACE 
            FUNCTION AVERAGEVAL(ARR,NUMVAL)
              REAL(KIND=4) :: ARR(5000)
              INTEGER(KIND=4) :: NUMVAL
              REAL(KIND=4) :: AVERAGEVAL
            END FUNCTION AVERAGEVAL
          END INTERFACE 
        END MODULE AVERAGEVAL__genmod
