        !COMPILER-GENERATED INTERFACE MODULE: Tue Dec 06 10:14:12 2016
        MODULE CALCNIR__genmod
          INTERFACE 
            SUBROUTINE CALCNIR(RADABV,FBEAM)
              REAL(KIND=4) :: RADABV(96,3)
              REAL(KIND=4) :: FBEAM(96,3)
            END SUBROUTINE CALCNIR
          END INTERFACE 
        END MODULE CALCNIR__genmod
