        !COMPILER-GENERATED INTERFACE MODULE: Wed Nov 30 18:21:10 2016
        MODULE CALCPARHRLY__genmod
          INTERFACE 
            SUBROUTINE CALCPARHRLY(RADBM,RADDF,ZEN,RADABV,FBEAM)
              REAL(KIND=4) :: RADBM
              REAL(KIND=4) :: RADDF
              REAL(KIND=4) :: ZEN(96)
              REAL(KIND=4) :: RADABV(96,3)
              REAL(KIND=4) :: FBEAM(96,3)
            END SUBROUTINE CALCPARHRLY
          END INTERFACE 
        END MODULE CALCPARHRLY__genmod
