        !COMPILER-GENERATED INTERFACE MODULE: Tue Dec 06 10:14:12 2016
        MODULE CALCFSUN__genmod
          INTERFACE 
            SUBROUTINE CALCFSUN(FBEAM,FSUN)
              REAL(KIND=4) :: FBEAM(96,3)
              REAL(KIND=4) :: FSUN(96)
            END SUBROUTINE CALCFSUN
          END INTERFACE 
        END MODULE CALCFSUN__genmod
