        !COMPILER-GENERATED INTERFACE MODULE: Wed Nov 23 15:25:56 2016
        MODULE CALCFSUN__genmod
          INTERFACE 
            SUBROUTINE CALCFSUN(FBEAM,FSUN)
              REAL(KIND=4) :: FBEAM(96,3)
              REAL(KIND=4) :: FSUN(96)
            END SUBROUTINE CALCFSUN
          END INTERFACE 
        END MODULE CALCFSUN__genmod
