        !COMPILER-GENERATED INTERFACE MODULE: Tue Sep 06 12:06:53 2016
        MODULE CALCELP__genmod
          INTERFACE 
            FUNCTION CALCELP(AVGANG)
              REAL(KIND=4) :: AVGANG
              REAL(KIND=4) :: CALCELP
            END FUNCTION CALCELP
          END INTERFACE 
        END MODULE CALCELP__genmod
