        !COMPILER-GENERATED INTERFACE MODULE: Tue Dec 06 10:14:10 2016
        MODULE CLOSEF__genmod
          INTERFACE 
            SUBROUTINE CLOSEF
            END SUBROUTINE CLOSEF
          END INTERFACE 
        END MODULE CLOSEF__genmod
