        !COMPILER-GENERATED INTERFACE MODULE: Wed Nov 23 15:25:53 2016
        MODULE DAYJUL__genmod
          INTERFACE 
            FUNCTION DAYJUL(IDATE)
              INTEGER(KIND=4) :: IDATE
              INTEGER(KIND=4) :: DAYJUL
            END FUNCTION DAYJUL
          END INTERFACE 
        END MODULE DAYJUL__genmod
