        !COMPILER-GENERATED INTERFACE MODULE: Tue Sep 06 12:06:39 2016
        MODULE DIVFOURNEAR__genmod
          INTERFACE 
            FUNCTION DIVFOURNEAR(NUM)
              INTEGER(KIND=4) :: NUM
              INTEGER(KIND=4) :: DIVFOURNEAR
            END FUNCTION DIVFOURNEAR
          END INTERFACE 
        END MODULE DIVFOURNEAR__genmod
