        !COMPILER-GENERATED INTERFACE MODULE: Wed Nov 30 18:21:12 2016
        MODULE DIVFOURNEAR__genmod
          INTERFACE 
            FUNCTION DIVFOURNEAR(NUM)
              INTEGER(KIND=4) :: NUM
              INTEGER(KIND=4) :: DIVFOURNEAR
            END FUNCTION DIVFOURNEAR
          END INTERFACE 
        END MODULE DIVFOURNEAR__genmod
