        !COMPILER-GENERATED INTERFACE MODULE: Tue Dec 06 10:14:13 2016
        MODULE ESOILFUN__genmod
          INTERFACE 
            FUNCTION ESOILFUN(SOILTK)
              REAL(KIND=4) :: SOILTK
              REAL(KIND=4) :: ESOILFUN
            END FUNCTION ESOILFUN
          END INTERFACE 
        END MODULE ESOILFUN__genmod
