        !COMPILER-GENERATED INTERFACE MODULE: Tue Sep 06 12:06:48 2016
        MODULE ESOILFUN__genmod
          INTERFACE 
            FUNCTION ESOILFUN(SOILTK)
              REAL(KIND=4) :: SOILTK
              REAL(KIND=4) :: ESOILFUN
            END FUNCTION ESOILFUN
          END INTERFACE 
        END MODULE ESOILFUN__genmod
