        !COMPILER-GENERATED INTERFACE MODULE: Wed Nov 23 15:25:53 2016
        MODULE GETRGLOB__genmod
          INTERFACE 
            SUBROUTINE GETRGLOB(IHOUR,SCLOSTTREE,THRAB,RADABV,NOTARGETS,&
     &NOALLTREES,PLOTAREA,ISIMUS,THRABUS,PARUSMEAN,DOWNTHTREE,EXPFACTORS&
     &,RGLOBABV,RGLOBABV12,RGLOBUND,RADINTERC12,RADINTERC1,RADINTERC2,  &
     &RADINTERC3,SCLOSTTOT,FRACAPAR,RADINTERC,RGLOBUND1,RGLOBUND2,      &
     &DOWNTHAV,SCLOSTTOT3,TOTLAI,TSOIL,RHOSOL)
              INTEGER(KIND=4) :: IHOUR
              REAL(KIND=4) :: SCLOSTTREE(5000,3)
              REAL(KIND=4) :: THRAB(5000,96,3)
              REAL(KIND=4) :: RADABV(96,3)
              INTEGER(KIND=4) :: NOTARGETS
              INTEGER(KIND=4) :: NOALLTREES
              REAL(KIND=4) :: PLOTAREA
              INTEGER(KIND=4) :: ISIMUS
              REAL(KIND=4) :: THRABUS
              REAL(KIND=4) :: PARUSMEAN
              REAL(KIND=4) :: DOWNTHTREE(5000)
              REAL(KIND=4) :: EXPFACTORS(5000)
              REAL(KIND=4) :: RGLOBABV
              REAL(KIND=4) :: RGLOBABV12
              REAL(KIND=4) :: RGLOBUND
              REAL(KIND=4) :: RADINTERC12
              REAL(KIND=4) :: RADINTERC1
              REAL(KIND=4) :: RADINTERC2
              REAL(KIND=4) :: RADINTERC3
              REAL(KIND=4) :: SCLOSTTOT
              REAL(KIND=4) :: FRACAPAR
              REAL(KIND=4) :: RADINTERC
              REAL(KIND=4) :: RGLOBUND1
              REAL(KIND=4) :: RGLOBUND2
              REAL(KIND=4) :: DOWNTHAV
              REAL(KIND=4) :: SCLOSTTOT3
              REAL(KIND=4) :: TOTLAI
              REAL(KIND=4) :: TSOIL
              REAL(KIND=4) :: RHOSOL(3)
            END SUBROUTINE GETRGLOB
          END INTERFACE 
        END MODULE GETRGLOB__genmod
