        !COMPILER-GENERATED INTERFACE MODULE: Tue Dec 06 10:14:12 2016
        MODULE GETWIND__genmod
          INTERFACE 
            SUBROUTINE GETWIND(FOLLAY,FOLNTR,TOTLAI,EXTWIND,WINDLAY)
              REAL(KIND=4) :: FOLLAY(15)
              REAL(KIND=4) :: FOLNTR
              REAL(KIND=4) :: TOTLAI
              REAL(KIND=4) :: EXTWIND
              REAL(KIND=4) :: WINDLAY(15)
            END SUBROUTINE GETWIND
          END INTERFACE 
        END MODULE GETWIND__genmod
