        !COMPILER-GENERATED INTERFACE MODULE: Wed Nov 30 18:21:10 2016
        MODULE GRADIATION__genmod
          INTERFACE 
            FUNCTION GRADIATION(TAIR,RDFIPT,TUIPT,TDIPT)
              REAL(KIND=4) :: TAIR
              REAL(KIND=4) :: RDFIPT
              REAL(KIND=4) :: TUIPT
              REAL(KIND=4) :: TDIPT
              REAL(KIND=4) :: GRADIATION
            END FUNCTION GRADIATION
          END INTERFACE 
        END MODULE GRADIATION__genmod
