        !COMPILER-GENERATED INTERFACE MODULE: Tue Dec 06 10:14:12 2016
        MODULE HEATEVAP__genmod
          INTERFACE 
            FUNCTION HEATEVAP(TAIR)
              REAL(KIND=4) :: TAIR
              REAL(KIND=4) :: HEATEVAP
            END FUNCTION HEATEVAP
          END INTERFACE 
        END MODULE HEATEVAP__genmod
