        !COMPILER-GENERATED INTERFACE MODULE: Wed Nov 30 18:21:11 2016
        MODULE IDATEYR__genmod
          INTERFACE 
            FUNCTION IDATEYR(STRDATE,IYEAR)
              CHARACTER(LEN=8) :: STRDATE
              INTEGER(KIND=4) :: IYEAR
              INTEGER(KIND=4) :: IDATEYR
            END FUNCTION IDATEYR
          END INTERFACE 
        END MODULE IDATEYR__genmod
