        !COMPILER-GENERATED INTERFACE MODULE: Wed Nov 23 15:25:51 2016
        MODULE IDATE50__genmod
          INTERFACE 
            FUNCTION IDATE50(STRDATE)
              CHARACTER(LEN=8) :: STRDATE
              INTEGER(KIND=4) :: IDATE50
            END FUNCTION IDATE50
          END INTERFACE 
        END MODULE IDATE50__genmod
