        !COMPILER-GENERATED INTERFACE MODULE: Tue Dec 06 10:14:09 2016
        MODULE INFILTRATE__genmod
          INTERFACE 
            SUBROUTINE INFILTRATE(SURFACE_WATERMM,NLAYER,POREFRAC,      &
     &FRACWATER,LAYTHICK,WATERGAIN,WATERLOSS,EXPINF,PPTGAIN,OVERFLOW)
              REAL(KIND=4) :: SURFACE_WATERMM
              INTEGER(KIND=4) :: NLAYER
              REAL(KIND=4) :: POREFRAC(51)
              REAL(KIND=4) :: FRACWATER(51)
              REAL(KIND=4) :: LAYTHICK(51)
              REAL(KIND=4) :: WATERGAIN(51)
              REAL(KIND=4) :: WATERLOSS(51)
              REAL(KIND=4) :: EXPINF
              REAL(KIND=4) :: PPTGAIN(51)
              REAL(KIND=4) :: OVERFLOW
            END SUBROUTINE INFILTRATE
          END INTERFACE 
        END MODULE INFILTRATE__genmod
