        !COMPILER-GENERATED INTERFACE MODULE: Tue Dec 06 10:14:12 2016
        MODULE JDATE__genmod
          INTERFACE 
            FUNCTION JDATE(IDATE50)
              INTEGER(KIND=4) :: IDATE50
              INTEGER(KIND=4) :: JDATE
            END FUNCTION JDATE
          END INTERFACE 
        END MODULE JDATE__genmod
