        !COMPILER-GENERATED INTERFACE MODULE: Tue Dec 06 10:14:11 2016
        MODULE OPEN_FILE__genmod
          INTERFACE 
            SUBROUTINE OPEN_FILE(FNAME,UNIT,ACTION,FILE_FORMAT,STATUS)
              CHARACTER(*) :: FNAME
              INTEGER(KIND=4) :: UNIT
              CHARACTER(*) :: ACTION
              CHARACTER(*) :: FILE_FORMAT
              CHARACTER(*) :: STATUS
            END SUBROUTINE OPEN_FILE
          END INTERFACE 
        END MODULE OPEN_FILE__genmod
