        !COMPILER-GENERATED INTERFACE MODULE: Wed Nov 23 15:25:55 2016
        MODULE OUTPUTDYWAT__genmod
          INTERFACE 
            SUBROUTINE OUTPUTDYWAT(IDAY,WSOILMEAN,WSOILROOTMEAN,SWPMEAN,&
     &PPTTOT,ETMMTOT,ETMEASTOT,DISCHARGETOT,SOILEVAPTOT,FSOILMEAN,      &
     &TFALLTOT,QHTOT,QETOT,QNTOT,QCTOT,RADINTERCTOT)
              INTEGER(KIND=4) :: IDAY
              REAL(KIND=4) :: WSOILMEAN
              REAL(KIND=4) :: WSOILROOTMEAN
              REAL(KIND=4) :: SWPMEAN
              REAL(KIND=4) :: PPTTOT
              REAL(KIND=4) :: ETMMTOT
              REAL(KIND=4) :: ETMEASTOT
              REAL(KIND=4) :: DISCHARGETOT
              REAL(KIND=4) :: SOILEVAPTOT
              REAL(KIND=4) :: FSOILMEAN
              REAL(KIND=4) :: TFALLTOT
              REAL(KIND=4) :: QHTOT
              REAL(KIND=4) :: QETOT
              REAL(KIND=4) :: QNTOT
              REAL(KIND=4) :: QCTOT
              REAL(KIND=4) :: RADINTERCTOT
            END SUBROUTINE OUTPUTDYWAT
          END INTERFACE 
        END MODULE OUTPUTDYWAT__genmod
