        !COMPILER-GENERATED INTERFACE MODULE: Tue Dec 06 10:14:11 2016
        MODULE OUTPUTHIST__genmod
          INTERFACE 
            SUBROUTINE OUTPUTHIST(UFILE,HISTO,BINSIZE,NOTARGETS)
              INTEGER(KIND=4) :: UFILE
              REAL(KIND=4) :: HISTO(5000,200)
              REAL(KIND=4) :: BINSIZE
              INTEGER(KIND=4) :: NOTARGETS
            END SUBROUTINE OUTPUTHIST
          END INTERFACE 
        END MODULE OUTPUTHIST__genmod
