        !COMPILER-GENERATED INTERFACE MODULE: Wed Nov 23 15:25:55 2016
        MODULE PHYINTERP2__genmod
          INTERFACE 
            SUBROUTINE PHYINTERP2(IDATE,NODATES,IDATEARR,PARAMTABLE,    &
     &PARAM)
              INTEGER(KIND=4) :: IDATE
              INTEGER(KIND=4) :: NODATES
              INTEGER(KIND=4) :: IDATEARR(45)
              REAL(KIND=4) :: PARAMTABLE(45)
              REAL(KIND=4) :: PARAM
            END SUBROUTINE PHYINTERP2
          END INTERFACE 
        END MODULE PHYINTERP2__genmod
