        !COMPILER-GENERATED INTERFACE MODULE: Wed Nov 23 15:25:55 2016
        MODULE READINFILT__genmod
          INTERFACE 
            SUBROUTINE READINFILT(UFILE,EXPINFI)
              INTEGER(KIND=4) :: UFILE
              REAL(KIND=4) :: EXPINFI
            END SUBROUTINE READINFILT
          END INTERFACE 
        END MODULE READINFILT__genmod
