        !COMPILER-GENERATED INTERFACE MODULE: Tue Dec 06 10:14:11 2016
        MODULE READWATTFALL__genmod
          INTERFACE 
            SUBROUTINE READWATTFALL(UFILE,RUTTERBI,RUTTERDI,MAXSTORAGEI,&
     &THROUGHFALLI)
              INTEGER(KIND=4) :: UFILE
              REAL(KIND=4) :: RUTTERBI
              REAL(KIND=4) :: RUTTERDI
              REAL(KIND=4) :: MAXSTORAGEI
              REAL(KIND=4) :: THROUGHFALLI
            END SUBROUTINE READWATTFALL
          END INTERFACE 
        END MODULE READWATTFALL__genmod
