        !COMPILER-GENERATED INTERFACE MODULE: Wed Nov 30 18:21:15 2016
        MODULE READPHYARRAY__genmod
          INTERFACE 
            SUBROUTINE READPHYARRAY(UFILE,NARRAY,NOLAY,NOAGEP,NDATE,    &
     &IDATES,VALUESI)
              INTEGER(KIND=4) :: UFILE
              INTEGER(KIND=4) :: NARRAY
              INTEGER(KIND=4) :: NOLAY
              INTEGER(KIND=4) :: NOAGEP
              INTEGER(KIND=4) :: NDATE
              INTEGER(KIND=4) :: IDATES(45)
              REAL(KIND=4) :: VALUESI(45,15,3)
            END SUBROUTINE READPHYARRAY
          END INTERFACE 
        END MODULE READPHYARRAY__genmod
