        !COMPILER-GENERATED INTERFACE MODULE: Tue Dec 06 10:14:11 2016
        MODULE READSPECLIST__genmod
          INTERFACE 
            SUBROUTINE READSPECLIST(UFILE,NSPECIES,ISPECIESI)
              INTEGER(KIND=4) :: UFILE
              INTEGER(KIND=4) :: NSPECIES
              INTEGER(KIND=4) :: ISPECIESI(5000)
            END SUBROUTINE READSPECLIST
          END INTERFACE 
        END MODULE READSPECLIST__genmod
