        !COMPILER-GENERATED INTERFACE MODULE: Wed Nov 30 18:21:15 2016
        MODULE READMODEL__genmod
          INTERFACE 
            SUBROUTINE READMODEL(UFILE,GSMODI,JMMODI,RDMODI,SSMODI,     &
     &RWMODI,ITERMAXI,ITERTAIRMAXI,NECHLAYI)
              INTEGER(KIND=4) :: UFILE
              INTEGER(KIND=4) :: GSMODI
              INTEGER(KIND=4) :: JMMODI
              INTEGER(KIND=4) :: RDMODI
              INTEGER(KIND=4) :: SSMODI
              INTEGER(KIND=4) :: RWMODI
              INTEGER(KIND=4) :: ITERMAXI
              INTEGER(KIND=4) :: ITERTAIRMAXI
              INTEGER(KIND=4) :: NECHLAYI
            END SUBROUTINE READMODEL
          END INTERFACE 
        END MODULE READMODEL__genmod
