        !COMPILER-GENERATED INTERFACE MODULE: Tue Dec 06 10:14:11 2016
        MODULE READZEN__genmod
          INTERFACE 
            SUBROUTINE READZEN(UFILE,NUMPNT,NOLAYI,PPLAYI,NZENI,NAZI,   &
     &DIFZEN)
              INTEGER(KIND=4) :: UFILE
              INTEGER(KIND=4) :: NUMPNT
              INTEGER(KIND=4) :: NOLAYI
              INTEGER(KIND=4) :: PPLAYI
              INTEGER(KIND=4) :: NZENI
              INTEGER(KIND=4) :: NAZI
              REAL(KIND=4) :: DIFZEN(20)
            END SUBROUTINE READZEN
          END INTERFACE 
        END MODULE READZEN__genmod
