        !COMPILER-GENERATED INTERFACE MODULE: Wed Nov 30 18:21:15 2016
        MODULE READPLANTSTORE__genmod
          INTERFACE 
            SUBROUTINE READPLANTSTORE(UFILE,STORECOEFI,STOREEXPI,       &
     &STOPSIMONEMPTYI)
              INTEGER(KIND=4) :: UFILE
              REAL(KIND=4) :: STORECOEFI
              REAL(KIND=4) :: STOREEXPI
              INTEGER(KIND=4) :: STOPSIMONEMPTYI
            END SUBROUTINE READPLANTSTORE
          END INTERFACE 
        END MODULE READPLANTSTORE__genmod
