        !COMPILER-GENERATED INTERFACE MODULE: Tue Sep 06 12:06:54 2016
        MODULE READAGEP__genmod
          INTERFACE 
            SUBROUTINE READAGEP(UFILE,NOAGEC,NOAGEPI)
              INTEGER(KIND=4) :: UFILE
              INTEGER(KIND=4) :: NOAGEC
              INTEGER(KIND=4) :: NOAGEPI
            END SUBROUTINE READAGEP
          END INTERFACE 
        END MODULE READAGEP__genmod
