        !COMPILER-GENERATED INTERFACE MODULE: Tue Dec 06 10:14:12 2016
        MODULE READDELTAT__genmod
          INTERFACE 
            SUBROUTINE READDELTAT(UFILE,DELTATI,IOERROR)
              INTEGER(KIND=4) :: UFILE
              REAL(KIND=4) :: DELTATI(12)
              INTEGER(KIND=4) :: IOERROR
            END SUBROUTINE READDELTAT
          END INTERFACE 
        END MODULE READDELTAT__genmod
