        !COMPILER-GENERATED INTERFACE MODULE: Tue Dec 06 10:14:12 2016
        MODULE READENVIRON__genmod
          INTERFACE 
            SUBROUTINE READENVIRON(UFILE,CAK,PRESSK,DIFSKYI,SWMINI,     &
     &SWMAXI)
              INTEGER(KIND=4) :: UFILE
              REAL(KIND=4) :: CAK
              REAL(KIND=4) :: PRESSK
              REAL(KIND=4) :: DIFSKYI
              REAL(KIND=4) :: SWMINI
              REAL(KIND=4) :: SWMAXI
            END SUBROUTINE READENVIRON
          END INTERFACE 
        END MODULE READENVIRON__genmod
