        !COMPILER-GENERATED INTERFACE MODULE: Wed Nov 23 15:25:55 2016
        MODULE READAERO__genmod
          INTERFACE 
            SUBROUTINE READAERO(UFILE,EXTWINDI)
              INTEGER(KIND=4) :: UFILE
              REAL(KIND=4) :: EXTWINDI
            END SUBROUTINE READAERO
          END INTERFACE 
        END MODULE READAERO__genmod
