        !COMPILER-GENERATED INTERFACE MODULE: Tue Dec 06 10:14:11 2016
        MODULE READAERO__genmod
          INTERFACE 
            SUBROUTINE READAERO(UFILE,EXTWINDI)
              INTEGER(KIND=4) :: UFILE
              REAL(KIND=4) :: EXTWINDI
            END SUBROUTINE READAERO
          END INTERFACE 
        END MODULE READAERO__genmod
