        !COMPILER-GENERATED INTERFACE MODULE: Tue Dec 06 10:14:11 2016
        MODULE READLIA__genmod
          INTERFACE 
            SUBROUTINE READLIA(UFILE,NALPHAI,ALPHA,FALPHAI,DATESLIAOUT, &
     &NOLIADATES)
              INTEGER(KIND=4) :: UFILE
              INTEGER(KIND=4) :: NALPHAI
              REAL(KIND=4) :: ALPHA(20)
              REAL(KIND=4) :: FALPHAI(20,45)
              INTEGER(KIND=4) :: DATESLIAOUT(45)
              INTEGER(KIND=4) :: NOLIADATES
            END SUBROUTINE READLIA
          END INTERFACE 
        END MODULE READLIA__genmod
