        !COMPILER-GENERATED INTERFACE MODULE: Wed Nov 30 18:21:15 2016
        MODULE READROOTPARS__genmod
          INTERFACE 
            SUBROUTINE READROOTPARS(UFILE,NOSPEC,ROOTRESFRACI,          &
     &ROOTRADTABLEI,ROOTSRLTABLEI,ROOTMASSTOTTABLEI,NROOTLAYERI,        &
     &FRACROOTI,LAYTHICK,ROOTBETA,DATESROOTI,NOROOTDATES,NOROOTSPEC,    &
     &RFAGEBEGINI,RFPAR1I,RFPAR2I,RFPAR3I,ROOTFRONTLIMITI)
              INTEGER(KIND=4) :: UFILE
              INTEGER(KIND=4) :: NOSPEC
              REAL(KIND=4) :: ROOTRESFRACI
              REAL(KIND=4) :: ROOTRADTABLEI(45)
              REAL(KIND=4) :: ROOTSRLTABLEI(45)
              REAL(KIND=4) :: ROOTMASSTOTTABLEI(45)
              INTEGER(KIND=4) :: NROOTLAYERI
              REAL(KIND=4) :: FRACROOTI(51,45,5)
              REAL(KIND=4) :: LAYTHICK(51)
              REAL(KIND=4) :: ROOTBETA
              INTEGER(KIND=4) :: DATESROOTI(45)
              INTEGER(KIND=4) :: NOROOTDATES
              INTEGER(KIND=4) :: NOROOTSPEC
              INTEGER(KIND=4) :: RFAGEBEGINI(5)
              REAL(KIND=4) :: RFPAR1I(5)
              REAL(KIND=4) :: RFPAR2I(5)
              REAL(KIND=4) :: RFPAR3I(5)
              INTEGER(KIND=4) :: ROOTFRONTLIMITI
            END SUBROUTINE READROOTPARS
          END INTERFACE 
        END MODULE READROOTPARS__genmod
