        !COMPILER-GENERATED INTERFACE MODULE: Tue Dec 06 10:14:11 2016
        MODULE READARRAY__genmod
          INTERFACE 
            SUBROUTINE READARRAY(UFILE,INDEX,NDATESI,DATESI,RATES)
              INTEGER(KIND=4) :: UFILE
              INTEGER(KIND=4) :: INDEX
              INTEGER(KIND=4) :: NDATESI
              INTEGER(KIND=4) :: DATESI(45)
              REAL(KIND=4) :: RATES(45)
            END SUBROUTINE READARRAY
          END INTERFACE 
        END MODULE READARRAY__genmod
