        !COMPILER-GENERATED INTERFACE MODULE: Tue Sep 06 12:06:54 2016
        MODULE READSPECIES__genmod
          INTERFACE 
            SUBROUTINE READSPECIES(UFILE,NSPECIES,SPECIESNAMES,PHYFILES,&
     &STRFILES)
              INTEGER(KIND=4) :: UFILE
              INTEGER(KIND=4) :: NSPECIES
              CHARACTER(LEN=30) :: SPECIESNAMES(4)
              CHARACTER(LEN=30) :: PHYFILES(4)
              CHARACTER(LEN=30) :: STRFILES(4)
            END SUBROUTINE READSPECIES
          END INTERFACE 
        END MODULE READSPECIES__genmod
