        !COMPILER-GENERATED INTERFACE MODULE: Wed Nov 23 15:25:55 2016
        MODULE READPLANTPARS__genmod
          INTERFACE 
            SUBROUTINE READPLANTPARS(UFILE,MINROOTWPI,MINLEAFWPI,       &
     &PLANTKTABLEI,KSCALINGI,DATESKPI,NOKPDATES)
              INTEGER(KIND=4) :: UFILE
              REAL(KIND=4) :: MINROOTWPI
              REAL(KIND=4) :: MINLEAFWPI(5)
              REAL(KIND=4) :: PLANTKTABLEI(45)
              REAL(KIND=4) :: KSCALINGI
              INTEGER(KIND=4) :: DATESKPI(45)
              INTEGER(KIND=4) :: NOKPDATES
            END SUBROUTINE READPLANTPARS
          END INTERFACE 
        END MODULE READPLANTPARS__genmod
