        !COMPILER-GENERATED INTERFACE MODULE: Tue Sep 06 12:06:56 2016
        MODULE RESTARTMETF__genmod
          INTERFACE 
            SUBROUTINE RESTARTMETF(ISTART,MSTART,MFLAG)
              INTEGER(KIND=4) :: ISTART
              INTEGER(KIND=4) :: MSTART
              INTEGER(KIND=4) :: MFLAG
            END SUBROUTINE RESTARTMETF
          END INTERFACE 
        END MODULE RESTARTMETF__genmod
