        !COMPILER-GENERATED INTERFACE MODULE: Tue Dec 06 10:14:12 2016
        MODULE SKIPMET__genmod
          INTERFACE 
            SUBROUTINE SKIPMET(MFLAG,NSTEP)
              INTEGER(KIND=4) :: MFLAG
              INTEGER(KIND=4) :: NSTEP
            END SUBROUTINE SKIPMET
          END INTERFACE 
        END MODULE SKIPMET__genmod
