        !COMPILER-GENERATED INTERFACE MODULE: Wed Nov 23 15:25:54 2016
        MODULE SORTTREESI__genmod
          INTERFACE 
            SUBROUTINE SORTTREESI(NOALLTREES,NOTREES,NOTARGET,DX,DY,DZ, &
     &IT)
              INTEGER(KIND=4) :: NOALLTREES
              INTEGER(KIND=4) :: NOTREES
              INTEGER(KIND=4) :: NOTARGET
              REAL(KIND=4) :: DX(5000)
              REAL(KIND=4) :: DY(5000)
              REAL(KIND=4) :: DZ(5000)
              INTEGER(KIND=4) :: IT(5000)
            END SUBROUTINE SORTTREESI
          END INTERFACE 
        END MODULE SORTTREESI__genmod
