        !COMPILER-GENERATED INTERFACE MODULE: Tue Dec 06 10:14:12 2016
        MODULE SUBERROR__genmod
          INTERFACE 
            SUBROUTINE SUBERROR(MESSAGE,IFLAG,IOERROR)
              CHARACTER(*) :: MESSAGE
              INTEGER(KIND=4) :: IFLAG
              INTEGER(KIND=4) :: IOERROR
            END SUBROUTINE SUBERROR
          END INTERFACE 
        END MODULE SUBERROR__genmod
