        !COMPILER-GENERATED INTERFACE MODULE: Tue Sep 06 12:06:39 2016
        MODULE SUBERROR__genmod
          INTERFACE 
            SUBROUTINE SUBERROR(MESSAGE,IFLAG,IOERROR)
              CHARACTER(*) :: MESSAGE
              INTEGER(KIND=4) :: IFLAG
              INTEGER(KIND=4) :: IOERROR
            END SUBROUTINE SUBERROR
          END INTERFACE 
        END MODULE SUBERROR__genmod
