        !COMPILER-GENERATED INTERFACE MODULE: Wed Nov 23 15:25:51 2016
        MODULE SUBERROR__genmod
          INTERFACE 
            SUBROUTINE SUBERROR(MESSAGE,IFLAG,IOERROR)
              CHARACTER(*) :: MESSAGE
              INTEGER(KIND=4) :: IFLAG
              INTEGER(KIND=4) :: IOERROR
            END SUBROUTINE SUBERROR
          END INTERFACE 
        END MODULE SUBERROR__genmod
