        !COMPILER-GENERATED INTERFACE MODULE: Tue Dec 06 10:14:09 2016
        MODULE VOLHCFUN__genmod
          INTERFACE 
            FUNCTION VOLHCFUN(POREFRAC,FRACWATER)
              REAL(KIND=4) :: POREFRAC
              REAL(KIND=4) :: FRACWATER
              REAL(KIND=4) :: VOLHCFUN
            END FUNCTION VOLHCFUN
          END INTERFACE 
        END MODULE VOLHCFUN__genmod
