        !COMPILER-GENERATED INTERFACE MODULE: Tue Sep 06 12:06:53 2016
        MODULE WRITE_HEADER_INFORMATION__genmod
          INTERFACE 
            SUBROUTINE WRITE_HEADER_INFORMATION(NSPECIES,SPECIESNAMES,  &
     &CTITLE,TTITLE,PTITLE,STITLE,MTITLE,WTITLE,VTITLE,ISMAESPA,ISIMUS)
              INTEGER(KIND=4) :: NSPECIES
              CHARACTER(LEN=30) :: SPECIESNAMES(4)
              CHARACTER(*), INTENT(IN) :: CTITLE
              CHARACTER(*), INTENT(IN) :: TTITLE
              CHARACTER(*), INTENT(IN) :: PTITLE
              CHARACTER(*), INTENT(IN) :: STITLE
              CHARACTER(*), INTENT(IN) :: MTITLE
              CHARACTER(*), INTENT(IN) :: WTITLE
              CHARACTER(*), INTENT(IN) :: VTITLE
              LOGICAL(KIND=4) :: ISMAESPA
              INTEGER(KIND=4) :: ISIMUS
            END SUBROUTINE WRITE_HEADER_INFORMATION
          END INTERFACE 
        END MODULE WRITE_HEADER_INFORMATION__genmod
