        !COMPILER-GENERATED INTERFACE MODULE: Fri Oct 07 14:37:29 2016
        MODULE ASSIGNFRACROOT__genmod
          INTERFACE 
            SUBROUTINE ASSIGNFRACROOT(ROOTBETA,FRACROOT,NROOTLAYER,     &
     &LAYTHICK)
              REAL(KIND=4) :: ROOTBETA
              REAL(KIND=4) :: FRACROOT(75)
              INTEGER(KIND=4) :: NROOTLAYER
              REAL(KIND=4) :: LAYTHICK(75)
            END SUBROUTINE ASSIGNFRACROOT
          END INTERFACE 
        END MODULE ASSIGNFRACROOT__genmod
