        !COMPILER-GENERATED INTERFACE MODULE: Fri Oct 07 14:37:31 2016
        MODULE CALCPARHRLY__genmod
          INTERFACE 
            SUBROUTINE CALCPARHRLY(RADBM,RADDF,ZEN,RADABV,FBEAM)
              REAL(KIND=4) :: RADBM
              REAL(KIND=4) :: RADDF
              REAL(KIND=4) :: ZEN(300)
              REAL(KIND=4) :: RADABV(300,3)
              REAL(KIND=4) :: FBEAM(300,3)
            END SUBROUTINE CALCPARHRLY
          END INTERFACE 
        END MODULE CALCPARHRLY__genmod
