        !COMPILER-GENERATED INTERFACE MODULE: Fri Oct 07 14:37:31 2016
        MODULE CALCTSOIL__genmod
          INTERFACE 
            SUBROUTINE CALCTSOIL(TAIR,TSOIL)
              REAL(KIND=4) :: TAIR(300)
              REAL(KIND=4) :: TSOIL(300)
            END SUBROUTINE CALCTSOIL
          END INTERFACE 
        END MODULE CALCTSOIL__genmod
