        !COMPILER-GENERATED INTERFACE MODULE: Fri Oct 07 14:37:31 2016
        MODULE CALCTHRLY__genmod
          INTERFACE 
            SUBROUTINE CALCTHRLY(TMAX,TMIN,DAYL,TAIR)
              REAL(KIND=4) :: TMAX
              REAL(KIND=4) :: TMIN
              REAL(KIND=4) :: DAYL
              REAL(KIND=4) :: TAIR(300)
            END SUBROUTINE CALCTHRLY
          END INTERFACE 
        END MODULE CALCTHRLY__genmod
