        !COMPILER-GENERATED INTERFACE MODULE: Fri Oct 07 14:37:27 2016
        MODULE DEFAULT_CONDITIONS__genmod
          INTERFACE 
            SUBROUTINE DEFAULT_CONDITIONS(IN_PATH,OUT_PATH)
              CHARACTER(*), INTENT(INOUT) :: IN_PATH
              CHARACTER(*), INTENT(INOUT) :: OUT_PATH
            END SUBROUTINE DEFAULT_CONDITIONS
          END INTERFACE 
        END MODULE DEFAULT_CONDITIONS__genmod
