        !COMPILER-GENERATED INTERFACE MODULE: Fri Oct 07 14:37:29 2016
        MODULE DISTINTERP__genmod
          INTERFACE 
            SUBROUTINE DISTINTERP(IDAY,ISTART,NODATES,NOMAX,IDATEARR,   &
     &PARAMTABLE,PARAM)
              INTEGER(KIND=4) :: IDAY
              INTEGER(KIND=4) :: ISTART
              INTEGER(KIND=4) :: NODATES
              INTEGER(KIND=4) :: NOMAX
              INTEGER(KIND=4) :: IDATEARR(30)
              REAL(KIND=4) :: PARAMTABLE(75,30)
              REAL(KIND=4) :: PARAM(75)
            END SUBROUTINE DISTINTERP
          END INTERFACE 
        END MODULE DISTINTERP__genmod
