        !COMPILER-GENERATED INTERFACE MODULE: Fri Oct 07 14:37:27 2016
        MODULE DIVFOURNEAR__genmod
          INTERFACE 
            FUNCTION DIVFOURNEAR(NUM)
              INTEGER(KIND=4) :: NUM
              INTEGER(KIND=4) :: DIVFOURNEAR
            END FUNCTION DIVFOURNEAR
          END INTERFACE 
        END MODULE DIVFOURNEAR__genmod
