        !COMPILER-GENERATED INTERFACE MODULE: Fri Oct 07 14:37:31 2016
        MODULE ENERGYFUN__genmod
          INTERFACE 
            FUNCTION ENERGYFUN(SOILTK,EXTRAPARS,EXTRAINT)
              REAL(KIND=4) :: SOILTK
              REAL(KIND=4) :: EXTRAPARS(75)
              INTEGER(KIND=4) :: EXTRAINT(10)
              REAL(KIND=4) :: ENERGYFUN
            END FUNCTION ENERGYFUN
          END INTERFACE 
        END MODULE ENERGYFUN__genmod
