        !COMPILER-GENERATED INTERFACE MODULE: Fri Oct 07 14:37:28 2016
        MODULE ESOILFUN__genmod
          INTERFACE 
            FUNCTION ESOILFUN(SOILTK)
              REAL(KIND=4) :: SOILTK
              REAL(KIND=4) :: ESOILFUN
            END FUNCTION ESOILFUN
          END INTERFACE 
        END MODULE ESOILFUN__genmod
