        !COMPILER-GENERATED INTERFACE MODULE: Fri Oct 07 14:37:27 2016
        MODULE HEATEVAP__genmod
          INTERFACE 
            FUNCTION HEATEVAP(TAIR)
              REAL(KIND=4) :: TAIR
              REAL(KIND=4) :: HEATEVAP
            END FUNCTION HEATEVAP
          END INTERFACE 
        END MODULE HEATEVAP__genmod
