        !COMPILER-GENERATED INTERFACE MODULE: Fri Oct 07 14:37:27 2016
        MODULE IDATEYR__genmod
          INTERFACE 
            FUNCTION IDATEYR(STRDATE,IYEAR)
              CHARACTER(LEN=8) :: STRDATE
              INTEGER(KIND=4) :: IYEAR
              INTEGER(KIND=4) :: IDATEYR
            END FUNCTION IDATEYR
          END INTERFACE 
        END MODULE IDATEYR__genmod
