        !COMPILER-GENERATED INTERFACE MODULE: Fri Oct 07 14:37:30 2016
        MODULE INPUTWATBAL__genmod
          INTERFACE 
            SUBROUTINE INPUTWATBAL(BPAR,PSIE,KSAT,ROOTRESIST,ROOTRESFRAC&
     &,ROOTRADTABLE,ROOTSRLTABLE,ROOTMASSTOTTABLE,MINROOTWP,MINLEAFWP,  &
     &PLANTKTABLE,KSCALING,THROUGHFALL,REASSIGNRAIN,RUTTERB,RUTTERD,    &
     &MAXSTORAGE,DRAINLIMIT,ROOTXSECAREA,EQUALUPTAKE,NLAYER,NROOTLAYER, &
     &LAYTHICK,INITWATER,FRACROOT,POREFRAC,SOILTEMP,KEEPWET,DRYTHICKMIN,&
     &TORTPAR,SIMTSOIL,RETFUNCTION,FRACORGANIC,EXPINF,WSOILMETHOD,      &
     &USEMEASET,USEMEASSW,SIMSOILEVAP,USESTAND,ALPHARET,WS,WR,NRET,     &
     &DATESKP,NOKPDATES,DATESROOT,NOROOTDATES,IWATTABLAYER,ISIMWATTAB,  &
     &PLATDRAIN,RFAGEBEGIN,RFPAR1,RFPAR2,RFPAR3,ROOTFRONTLIMIT)
              REAL(KIND=4) :: BPAR(75)
              REAL(KIND=4) :: PSIE(75)
              REAL(KIND=4) :: KSAT(75)
              REAL(KIND=4) :: ROOTRESIST
              REAL(KIND=4) :: ROOTRESFRAC
              REAL(KIND=4) :: ROOTRADTABLE(30)
              REAL(KIND=4) :: ROOTSRLTABLE(30)
              REAL(KIND=4) :: ROOTMASSTOTTABLE(30)
              REAL(KIND=4) :: MINROOTWP
              REAL(KIND=4) :: MINLEAFWP
              REAL(KIND=4) :: PLANTKTABLE(30)
              REAL(KIND=4) :: KSCALING
              REAL(KIND=4) :: THROUGHFALL
              INTEGER(KIND=4) :: REASSIGNRAIN
              REAL(KIND=4) :: RUTTERB
              REAL(KIND=4) :: RUTTERD
              REAL(KIND=4) :: MAXSTORAGE
              REAL(KIND=4) :: DRAINLIMIT(75)
              REAL(KIND=4) :: ROOTXSECAREA
              INTEGER(KIND=4) :: EQUALUPTAKE
              INTEGER(KIND=4) :: NLAYER
              INTEGER(KIND=4) :: NROOTLAYER
              REAL(KIND=4) :: LAYTHICK(75)
              REAL(KIND=4) :: INITWATER(75)
              REAL(KIND=4) :: FRACROOT(75,30)
              REAL(KIND=4) :: POREFRAC(75)
              REAL(KIND=4) :: SOILTEMP(75)
              INTEGER(KIND=4) :: KEEPWET
              REAL(KIND=4) :: DRYTHICKMIN
              REAL(KIND=4) :: TORTPAR
              INTEGER(KIND=4) :: SIMTSOIL
              INTEGER(KIND=4) :: RETFUNCTION
              REAL(KIND=4) :: FRACORGANIC(75)
              REAL(KIND=4) :: EXPINF
              INTEGER(KIND=4) :: WSOILMETHOD
              INTEGER(KIND=4) :: USEMEASET
              INTEGER(KIND=4) :: USEMEASSW
              INTEGER(KIND=4) :: SIMSOILEVAP
              INTEGER(KIND=4) :: USESTAND
              REAL(KIND=4) :: ALPHARET(75)
              REAL(KIND=4) :: WS(75)
              REAL(KIND=4) :: WR(75)
              REAL(KIND=4) :: NRET(75)
              INTEGER(KIND=4) :: DATESKP(30)
              INTEGER(KIND=4) :: NOKPDATES
              INTEGER(KIND=4) :: DATESROOT(30)
              INTEGER(KIND=4) :: NOROOTDATES
              INTEGER(KIND=4) :: IWATTABLAYER
              INTEGER(KIND=4) :: ISIMWATTAB
              REAL(KIND=4) :: PLATDRAIN
              INTEGER(KIND=4) :: RFAGEBEGIN
              REAL(KIND=4) :: RFPAR1
              REAL(KIND=4) :: RFPAR2
              REAL(KIND=4) :: RFPAR3
              INTEGER(KIND=4) :: ROOTFRONTLIMIT
            END SUBROUTINE INPUTWATBAL
          END INTERFACE 
        END MODULE INPUTWATBAL__genmod
