        !COMPILER-GENERATED INTERFACE MODULE: Fri Oct 07 14:37:30 2016
        MODULE INTERPOLATEDIST__genmod
          INTERFACE 
            SUBROUTINE INTERPOLATEDIST(IDAY,ISTART,FRACROOTTABLE,       &
     &NOROOTDATES,DATESROOT,FRACROOT,NROOTLAYER,NALPHASPEC,             &
     &FALPHATABLESPEC,DATESLIA2,NOLIADATES,FALPHASPEC,NSPECIES,ISMAESPA,&
     &LAYTHICK,RFAGEBEGIN,RFPAR1,RFPAR2,RFPAR3,ROOTFRONTLIMIT,ROOTFRONT)
              INTEGER(KIND=4) :: IDAY
              INTEGER(KIND=4) :: ISTART
              REAL(KIND=4) :: FRACROOTTABLE(75,30)
              INTEGER(KIND=4) :: NOROOTDATES
              INTEGER(KIND=4) :: DATESROOT(30)
              REAL(KIND=4) :: FRACROOT(75)
              INTEGER(KIND=4) :: NROOTLAYER
              INTEGER(KIND=4) :: NALPHASPEC(5)
              REAL(KIND=4) :: FALPHATABLESPEC(20,30,5)
              INTEGER(KIND=4) :: DATESLIA2(30,5)
              INTEGER(KIND=4) :: NOLIADATES(5)
              REAL(KIND=4) :: FALPHASPEC(20,5)
              INTEGER(KIND=4) :: NSPECIES
              LOGICAL(KIND=4) :: ISMAESPA
              REAL(KIND=4) :: LAYTHICK(75)
              INTEGER(KIND=4) :: RFAGEBEGIN
              REAL(KIND=4) :: RFPAR1
              REAL(KIND=4) :: RFPAR2
              REAL(KIND=4) :: RFPAR3
              INTEGER(KIND=4) :: ROOTFRONTLIMIT
              REAL(KIND=4) :: ROOTFRONT
            END SUBROUTINE INTERPOLATEDIST
          END INTERFACE 
        END MODULE INTERPOLATEDIST__genmod
