        !COMPILER-GENERATED INTERFACE MODULE: Fri Oct 07 14:37:30 2016
        MODULE INTERPOLATEW__genmod
          INTERFACE 
            SUBROUTINE INTERPOLATEW(IDAY,ISTART,NOKPDATES,DATESKP,      &
     &PLANTKTABLE,PLANTK,NOROOTDATES,DATESROOT,ROOTRADTABLE,ROOTSRLTABLE&
     &,ROOTMASSTOTTABLE,FRACROOT,LAYTHICK,ROOTRESFRAC,ROOTXSECAREA,     &
     &ROOTLEN,ROOTRESIST,ROOTMASS,NROOTLAYER,ROOTRAD)
              INTEGER(KIND=4) :: IDAY
              INTEGER(KIND=4) :: ISTART
              INTEGER(KIND=4) :: NOKPDATES
              INTEGER(KIND=4) :: DATESKP(30)
              REAL(KIND=4) :: PLANTKTABLE(30)
              REAL(KIND=4) :: PLANTK
              INTEGER(KIND=4) :: NOROOTDATES
              INTEGER(KIND=4) :: DATESROOT(30)
              REAL(KIND=4) :: ROOTRADTABLE(30)
              REAL(KIND=4) :: ROOTSRLTABLE(30)
              REAL(KIND=4) :: ROOTMASSTOTTABLE(30)
              REAL(KIND=4) :: FRACROOT(75)
              REAL(KIND=4) :: LAYTHICK(75)
              REAL(KIND=4) :: ROOTRESFRAC
              REAL(KIND=4) :: ROOTXSECAREA
              REAL(KIND=4) :: ROOTLEN(75)
              REAL(KIND=4) :: ROOTRESIST
              REAL(KIND=4) :: ROOTMASS(75)
              INTEGER(KIND=4) :: NROOTLAYER
              REAL(KIND=4) :: ROOTRAD
            END SUBROUTINE INTERPOLATEW
          END INTERFACE 
        END MODULE INTERPOLATEW__genmod
