        !COMPILER-GENERATED INTERFACE MODULE: Fri Oct 07 14:37:29 2016
        MODULE OUTPUTHIST__genmod
          INTERFACE 
            SUBROUTINE OUTPUTHIST(UFILE,HISTO,BINSIZE,NOTARGETS)
              INTEGER(KIND=4) :: UFILE
              REAL(KIND=4) :: HISTO(5000,200)
              REAL(KIND=4) :: BINSIZE
              INTEGER(KIND=4) :: NOTARGETS
            END SUBROUTINE OUTPUTHIST
          END INTERFACE 
        END MODULE OUTPUTHIST__genmod
