        !COMPILER-GENERATED INTERFACE MODULE: Fri Oct 07 14:37:29 2016
        MODULE PHYINTERP2__genmod
          INTERFACE 
            SUBROUTINE PHYINTERP2(IDATE,NODATES,IDATEARR,PARAMTABLE,    &
     &PARAM)
              INTEGER(KIND=4) :: IDATE
              INTEGER(KIND=4) :: NODATES
              INTEGER(KIND=4) :: IDATEARR(30)
              REAL(KIND=4) :: PARAMTABLE(30)
              REAL(KIND=4) :: PARAM
            END SUBROUTINE PHYINTERP2
          END INTERFACE 
        END MODULE PHYINTERP2__genmod
