        !COMPILER-GENERATED INTERFACE MODULE: Fri Oct 07 14:37:29 2016
        MODULE READSOILEVAPPARS__genmod
          INTERFACE 
            SUBROUTINE READSOILEVAPPARS(UFILE,DRYTHICKMINI,TORTPARI)
              INTEGER(KIND=4) :: UFILE
              REAL(KIND=4) :: DRYTHICKMINI
              REAL(KIND=4) :: TORTPARI
            END SUBROUTINE READSOILEVAPPARS
          END INTERFACE 
        END MODULE READSOILEVAPPARS__genmod
