        !COMPILER-GENERATED INTERFACE MODULE: Fri Oct 07 14:37:30 2016
        MODULE READLEAFN__genmod
          INTERFACE 
            SUBROUTINE READLEAFN(UFILE,MODELJM,MODELRD,NOLAY,NOAGEP,    &
     &NONDATES,DATESN,VALUESN)
              INTEGER(KIND=4) :: UFILE
              INTEGER(KIND=4) :: MODELJM
              INTEGER(KIND=4) :: MODELRD
              INTEGER(KIND=4) :: NOLAY
              INTEGER(KIND=4) :: NOAGEP
              INTEGER(KIND=4) :: NONDATES
              INTEGER(KIND=4) :: DATESN(30)
              REAL(KIND=4) :: VALUESN(30,15,3)
            END SUBROUTINE READLEAFN
          END INTERFACE 
        END MODULE READLEAFN__genmod
