        !COMPILER-GENERATED INTERFACE MODULE: Fri Oct 07 14:37:29 2016
        MODULE READINFILT__genmod
          INTERFACE 
            SUBROUTINE READINFILT(UFILE,EXPINFI)
              INTEGER(KIND=4) :: UFILE
              REAL(KIND=4) :: EXPINFI
            END SUBROUTINE READINFILT
          END INTERFACE 
        END MODULE READINFILT__genmod
