        !COMPILER-GENERATED INTERFACE MODULE: Fri Oct 07 14:37:30 2016
        MODULE READTREEARRAY__genmod
          INTERFACE 
            SUBROUTINE READTREEARRAY(UFILE,NARRAY,NOALLTREES,NDATE,     &
     &IDATES,VALUESI)
              INTEGER(KIND=4) :: UFILE
              INTEGER(KIND=4) :: NARRAY
              INTEGER(KIND=4) :: NOALLTREES
              INTEGER(KIND=4) :: NDATE
              INTEGER(KIND=4) :: IDATES(30)
              REAL(KIND=4) :: VALUESI(30,5000)
            END SUBROUTINE READTREEARRAY
          END INTERFACE 
        END MODULE READTREEARRAY__genmod
