        !COMPILER-GENERATED INTERFACE MODULE: Fri Oct 07 14:37:29 2016
        MODULE READPLANTPARS__genmod
          INTERFACE 
            SUBROUTINE READPLANTPARS(UFILE,MINROOTWPI,MINLEAFWPI,       &
     &PLANTKTABLEI,KSCALINGI,DATESKPI,NOKPDATES)
              INTEGER(KIND=4) :: UFILE
              REAL(KIND=4) :: MINROOTWPI
              REAL(KIND=4) :: MINLEAFWPI
              REAL(KIND=4) :: PLANTKTABLEI(30)
              REAL(KIND=4) :: KSCALINGI
              INTEGER(KIND=4) :: DATESKPI(30)
              INTEGER(KIND=4) :: NOKPDATES
            END SUBROUTINE READPLANTPARS
          END INTERFACE 
        END MODULE READPLANTPARS__genmod
