        !COMPILER-GENERATED INTERFACE MODULE: Fri Oct 07 14:37:29 2016
        MODULE READINITPARS__genmod
          INTERFACE 
            SUBROUTINE READINITPARS(UFILE,INITWATERI,SOILTEMPI)
              INTEGER(KIND=4) :: UFILE
              REAL(KIND=4) :: INITWATERI(75)
              REAL(KIND=4) :: SOILTEMPI(75)
            END SUBROUTINE READINITPARS
          END INTERFACE 
        END MODULE READINITPARS__genmod
