        !COMPILER-GENERATED INTERFACE MODULE: Fri Oct 07 14:37:29 2016
        MODULE READLAYPARS__genmod
          INTERFACE 
            SUBROUTINE READLAYPARS(UFILE,NLAYERI,LAYTHICKI,COREWATERI,  &
     &POREFRACI,DRAINLIMITI,FRACORGANICI,IWATTABLAYERI,ISIMWATTABI,     &
     &PLATDRAINI)
              INTEGER(KIND=4) :: UFILE
              INTEGER(KIND=4) :: NLAYERI
              REAL(KIND=4) :: LAYTHICKI(75)
              REAL(KIND=4) :: COREWATERI
              REAL(KIND=4) :: POREFRACI(75)
              REAL(KIND=4) :: DRAINLIMITI(75)
              REAL(KIND=4) :: FRACORGANICI(75)
              INTEGER(KIND=4) :: IWATTABLAYERI
              INTEGER(KIND=4) :: ISIMWATTABI
              REAL(KIND=4) :: PLATDRAINI
            END SUBROUTINE READLAYPARS
          END INTERFACE 
        END MODULE READLAYPARS__genmod
