        !COMPILER-GENERATED INTERFACE MODULE: Fri Oct 07 14:37:29 2016
        MODULE READHIST__genmod
          INTERFACE 
            SUBROUTINE READHIST(UFILE,IOHIST,BINSIZEI)
              INTEGER(KIND=4) :: UFILE
              INTEGER(KIND=4) :: IOHIST
              REAL(KIND=4) :: BINSIZEI
            END SUBROUTINE READHIST
          END INTERFACE 
        END MODULE READHIST__genmod
