        !COMPILER-GENERATED INTERFACE MODULE: Fri Oct 07 14:37:29 2016
        MODULE READWATTFALL__genmod
          INTERFACE 
            SUBROUTINE READWATTFALL(UFILE,RUTTERBI,RUTTERDI,MAXSTORAGEI,&
     &THROUGHFALLI)
              INTEGER(KIND=4) :: UFILE
              REAL(KIND=4) :: RUTTERBI
              REAL(KIND=4) :: RUTTERDI
              REAL(KIND=4) :: MAXSTORAGEI
              REAL(KIND=4) :: THROUGHFALLI
            END SUBROUTINE READWATTFALL
          END INTERFACE 
        END MODULE READWATTFALL__genmod
