        !COMPILER-GENERATED INTERFACE MODULE: Fri Oct 07 14:37:30 2016
        MODULE READARRAY__genmod
          INTERFACE 
            SUBROUTINE READARRAY(UFILE,INDEX,NDATESI,DATESI,RATES)
              INTEGER(KIND=4) :: UFILE
              INTEGER(KIND=4) :: INDEX
              INTEGER(KIND=4) :: NDATESI
              INTEGER(KIND=4) :: DATESI(30)
              REAL(KIND=4) :: RATES(30)
            END SUBROUTINE READARRAY
          END INTERFACE 
        END MODULE READARRAY__genmod
