        !COMPILER-GENERATED INTERFACE MODULE: Fri Oct 07 14:37:29 2016
        MODULE READAGEP__genmod
          INTERFACE 
            SUBROUTINE READAGEP(UFILE,NOAGEC,NOAGEPI)
              INTEGER(KIND=4) :: UFILE
              INTEGER(KIND=4) :: NOAGEC
              INTEGER(KIND=4) :: NOAGEPI
            END SUBROUTINE READAGEP
          END INTERFACE 
        END MODULE READAGEP__genmod
