        !COMPILER-GENERATED INTERFACE MODULE: Fri Oct 07 14:37:31 2016
        MODULE RESTARTMETF__genmod
          INTERFACE 
            SUBROUTINE RESTARTMETF(ISTART,MSTART,MFLAG)
              INTEGER(KIND=4) :: ISTART
              INTEGER(KIND=4) :: MSTART
              INTEGER(KIND=4) :: MFLAG
            END SUBROUTINE RESTARTMETF
          END INTERFACE 
        END MODULE RESTARTMETF__genmod
