        !COMPILER-GENERATED INTERFACE MODULE: Fri Oct 07 14:37:27 2016
        MODULE SUBERROR__genmod
          INTERFACE 
            SUBROUTINE SUBERROR(MESSAGE,IFLAG,IOERROR)
              CHARACTER(*) :: MESSAGE
              INTEGER(KIND=4) :: IFLAG
              INTEGER(KIND=4) :: IOERROR
            END SUBROUTINE SUBERROR
          END INTERFACE 
        END MODULE SUBERROR__genmod
