        !COMPILER-GENERATED INTERFACE MODULE: Fri Oct 07 14:37:29 2016
        MODULE TREEINTERP2__genmod
          INTERFACE 
            SUBROUTINE TREEINTERP2(IDAY,ISTART,NODATES,IDATEARR,        &
     &PARAMTABLE,NOTREES,PARAMS)
              INTEGER(KIND=4) :: IDAY
              INTEGER(KIND=4) :: ISTART
              INTEGER(KIND=4) :: NODATES
              INTEGER(KIND=4) :: IDATEARR(30)
              REAL(KIND=4) :: PARAMTABLE(30)
              INTEGER(KIND=4) :: NOTREES
              REAL(KIND=4) :: PARAMS
            END SUBROUTINE TREEINTERP2
          END INTERFACE 
        END MODULE TREEINTERP2__genmod
