        !COMPILER-GENERATED INTERFACE MODULE: Fri Oct 07 14:37:31 2016
        MODULE VOLHCFUN__genmod
          INTERFACE 
            FUNCTION VOLHCFUN(POREFRAC,FRACWATER)
              REAL(KIND=4) :: POREFRAC
              REAL(KIND=4) :: FRACWATER
              REAL(KIND=4) :: VOLHCFUN
            END FUNCTION VOLHCFUN
          END INTERFACE 
        END MODULE VOLHCFUN__genmod
