        !COMPILER-GENERATED INTERFACE MODULE: Fri Oct 07 14:37:31 2016
        MODULE WATERTHERMAL__genmod
          INTERFACE 
            SUBROUTINE WATERTHERMAL(NLAYER,FRACWATER,POREFRAC,SOILTEMP, &
     &LAYTHICK,WATERGAIN,TAIRK,WATERLOSS,PPTGAIN,VOLHC)
              INTEGER(KIND=4) :: NLAYER
              REAL(KIND=4) :: FRACWATER(75)
              REAL(KIND=4) :: POREFRAC(75)
              REAL(KIND=4) :: SOILTEMP(75)
              REAL(KIND=4) :: LAYTHICK(75)
              REAL(KIND=4) :: WATERGAIN(75)
              REAL(KIND=4) :: TAIRK
              REAL(KIND=4) :: WATERLOSS(75)
              REAL(KIND=4) :: PPTGAIN(75)
              REAL(KIND=4) :: VOLHC(75)
            END SUBROUTINE WATERTHERMAL
          END INTERFACE 
        END MODULE WATERTHERMAL__genmod
